import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const translations = {
  vi: {
    interfaceLanguage: 'Ngôn ngữ giao diện', brandShort: 'Học tiếng Trung', brandTitle: 'Học tiếng Trung LiuLiuLiu',
    overview: 'Tổng quan', lessons: 'Bài học', vocabulary: 'Từ vựng', vocabularyPracticeResults: 'Luyện từ vựng', flashcards: 'Flashcard', listening: 'Luyện nghe', shadowing: 'Shadowing', writing: 'Luyện viết', progress: 'Tiến độ', settings: 'Cài đặt', grammar: 'Ngữ pháp', dialogues: 'Hội thoại', exercises: 'Bài tập', signOut: 'Đăng xuất', continueLesson: 'Tiếp tục Bài 1', reviewToday: 'Ôn tập hôm nay', recentProgress: 'Tiến độ gần đây', newFeedback: 'Phản hồi mới', content: 'Nội dung', students: 'Tài khoản', grading: 'Chấm bài', reports: 'Báo lỗi', analytics: 'Thống kê', admin: 'Quản trị viên', teacher: 'Giáo viên', submit: 'Nộp để chấm', practice: 'Tự luyện', saveDraft: 'Lưu bản nháp', answer: 'Đáp án', showAnswer: 'Xem đáp án', hideAnswer: 'Ẩn đáp án', source: 'Nguồn đối chiếu', pronunciation: 'Ngữ âm', profile: 'Tài khoản', notifications: 'Thông báo', home: 'Trang chủ', review: 'Ôn tập', login: 'Đăng nhập', register: 'Đăng ký', forgotPassword: 'Quên mật khẩu', displayName: 'Tên hiển thị', password: 'Mật khẩu', email: 'Email', emailVerification: 'Bạn cần xác thực email trước khi đăng nhập.',
    landingHeroTitle: 'Học tiếng Trung có lộ trình, luyện tập có phản hồi.',
    landingHeroDescription: 'Một không gian học trực tuyến dành cho học viên LiuLiuLiu: học từ nguồn giáo trình, luyện mỗi ngày và nhận nhận xét trực tiếp từ giáo viên.',
    startLearning: 'Bắt đầu học', haveAccount: 'Tôi đã có tài khoản', trustLine: 'Tài khoản email · Đồng bộ nhiều thiết bị · Chỉ hoạt động khi có mạng', lessonOne: 'Bài 1', helloMeaning: 'Xin chào · Hello', roadmapLabel: 'Lộ trình 15 bài', lessonsReady: '15 bài đều được mở sẵn', learningFeatures: 'Tính năng học tập',
    featureLessonsTitle: 'Học theo 15 bài', featureLessonsText: 'Từ vựng, ngữ pháp, hội thoại và bài tập cùng nằm trong một lộ trình rõ ràng.', featureAudioTitle: 'Nghe nguồn chính thức', featureAudioText: 'Luyện nghe và hội thoại bằng tệp âm thanh đi kèm giáo trình.', featureReviewTitle: 'Ôn đúng lúc', featureReviewText: 'Đánh dấu Chưa nhớ, Khó hoặc Đã nhớ để hệ thống sắp lịch ôn tập.', featureSubmitTitle: 'Tự luyện và nộp bài', featureSubmitText: 'Thu âm, luyện viết nhiều lần; mỗi bài chính thức chỉ nộp một lần để giáo viên chấm.', setupNote: 'Bản mã nguồn đã sẵn sàng; kết nối Supabase đang được hoàn tất cho môi trường xem trước.',
    publicHome: 'Trang giới thiệu', accountName: 'Tài khoản LiuLiuLiu', registerStudentTitle: 'Tạo tài khoản học viên', resetPasswordTitle: 'Đặt lại mật khẩu', choosePasswordTitle: 'Chọn mật khẩu mới', welcomeTitle: 'Chào mừng bạn trở lại', registerDescription: 'Học viên đăng ký bằng email và xác thực email trước khi bắt đầu học.', resetDescription: 'Mật khẩu mới cần có ít nhất 8 ký tự.', loginDescription: 'Học viên, giáo viên và quản trị viên đăng nhập tại cùng một nơi.',
    studentRegistration: 'Học viên', selfRegister: 'Tự đăng ký bằng email', teacherAccount: 'Giáo viên', ownerGrantsAccess: 'Chủ website cấp quyền', adminAccount: 'Quản trị viên', ownerOnlyAccess: 'Chủ website cấp quyền', staffLoginNote: 'Giáo viên và quản trị viên không tự chọn vai trò khi đăng ký. Hãy đăng nhập bằng tài khoản đã được chủ website cấp quyền.',
    newPassword: 'Mật khẩu mới', confirmPassword: 'Xác nhận mật khẩu', confirmNewPassword: 'Nhập lại mật khẩu mới', showPassword: 'Hiện mật khẩu', hidePassword: 'Ẩn mật khẩu', registerEmail: 'Đăng ký bằng email', sendResetLink: 'Gửi liên kết đặt lại', saveNewPassword: 'Lưu mật khẩu mới', alreadyRegistered: 'Đã có tài khoản? Đăng nhập', noAccount: 'Chưa có tài khoản? Đăng ký',
    authNotConfigured: 'Kết nối tài khoản trực tuyến đang được cấu hình cho bản xem trước.', accountCreated: 'Đã tạo tài khoản. Hãy mở email để xác thực trước khi đăng nhập.', emailConfirmed: 'Email đã được xác nhận thành công. Bạn có thể đăng nhập ngay.', emailConfirmationFailed: 'Không thể xác nhận email. Liên kết có thể đã hết hạn; vui lòng đăng ký lại hoặc yêu cầu liên kết mới.', resetSent: 'Đã gửi liên kết đặt lại mật khẩu vào email của bạn.', passwordMismatch: 'Hai mật khẩu chưa trùng nhau.', passwordChanged: 'Mật khẩu đã được đổi. Bạn có thể đăng nhập bằng mật khẩu mới.', authFailed: 'Không thể xử lý yêu cầu. Vui lòng thử lại.', itemUnit: 'mục', newLabel: 'Mới', teacherInitial: 'GV',
    accountManagement: 'Quản lý tài khoản', accountManagementDescription: 'Xem học viên và cấp quyền giáo viên hoặc quản trị viên.', accessPolicyTitle: 'Cách tạo tài khoản theo vai trò', accessPolicyText: 'Mọi người đăng ký bằng email với quyền học viên. Chủ website xác minh danh tính rồi nâng quyền trong trang này.', searchAccount: 'Tìm theo tên hoặc email', allRoles: 'Tất cả vai trò', role: 'Vai trò', status: 'Trạng thái', createdAt: 'Ngày tạo', actions: 'Thao tác', roleStudent: 'Học viên', roleTeacher: 'Giáo viên', roleAdmin: 'Quản trị viên', roleOwner: 'Chủ website', active: 'Đang hoạt động', locked: 'Đã khóa', lockAccount: 'Khóa', unlockAccount: 'Mở khóa', ownerProtected: 'Tài khoản chủ website được bảo vệ', accessUpdated: 'Đã cập nhật quyền tài khoản.', accessUpdateFailed: 'Không thể cập nhật quyền tài khoản.', accountsLoadFailed: 'Không thể tải danh sách tài khoản.', noAccounts: 'Không tìm thấy tài khoản phù hợp.', previewLabel: 'Bản xem trước',
  },
  en: {
    interfaceLanguage: 'Interface language', brandShort: 'Learn Chinese', brandTitle: 'Learn Chinese LiuLiuLiu',
    overview: 'Overview', lessons: 'Lessons', vocabulary: 'Vocabulary', vocabularyPracticeResults: 'Vocabulary practice', flashcards: 'Flashcards', listening: 'Listening', shadowing: 'Shadowing', writing: 'Writing', progress: 'Progress', settings: 'Settings', grammar: 'Grammar', dialogues: 'Dialogues', exercises: 'Exercises', signOut: 'Sign out', continueLesson: 'Continue Lesson 1', reviewToday: 'Review today', recentProgress: 'Recent progress', newFeedback: 'New feedback', content: 'Content', students: 'Accounts', grading: 'Grading', reports: 'Reports', analytics: 'Analytics', admin: 'Administrator', teacher: 'Teacher', submit: 'Submit for grading', practice: 'Self-practice', saveDraft: 'Save draft', answer: 'Answer', showAnswer: 'Show answer', hideAnswer: 'Hide answer', source: 'Source coverage', pronunciation: 'Pronunciation', profile: 'Account', notifications: 'Notifications', home: 'Home', review: 'Review', login: 'Sign in', register: 'Register', forgotPassword: 'Forgot password', displayName: 'Display name', password: 'Password', email: 'Email', emailVerification: 'Please verify your email before signing in.',
    landingHeroTitle: 'Learn Chinese with a clear path and teacher feedback.', landingHeroDescription: 'An online learning space for LiuLiuLiu students: learn from the course materials, practise every day, and receive direct teacher feedback.', startLearning: 'Start learning', haveAccount: 'I already have an account', trustLine: 'Email account · Multi-device sync · Online only', lessonOne: 'Lesson 1', helloMeaning: 'Hello · Xin chào', roadmapLabel: '15-lesson roadmap', lessonsReady: 'All 15 lessons are available', learningFeatures: 'Learning features', featureLessonsTitle: 'Learn through 15 lessons', featureLessonsText: 'Vocabulary, grammar, dialogues, and exercises follow one clear learning path.', featureAudioTitle: 'Official course audio', featureAudioText: 'Practise listening and dialogues with the audio supplied with the course.', featureReviewTitle: 'Review at the right time', featureReviewText: 'Mark words as Forgotten, Hard, or Remembered to schedule future reviews.', featureSubmitTitle: 'Practise and submit', featureSubmitText: 'Record and write as often as needed; each official task can be submitted once for grading.', setupNote: 'The source code is ready; Supabase is being connected for this preview environment.',
    publicHome: 'Introduction', accountName: 'LiuLiuLiu account', registerStudentTitle: 'Create a student account', resetPasswordTitle: 'Reset password', choosePasswordTitle: 'Choose a new password', welcomeTitle: 'Welcome back', registerDescription: 'Students register by email and verify it before learning.', resetDescription: 'Your new password must contain at least 8 characters.', loginDescription: 'Students, teachers, and administrators sign in from the same page.', studentRegistration: 'Student', selfRegister: 'Self-register by email', teacherAccount: 'Teacher', ownerGrantsAccess: 'Access granted by the site owner', adminAccount: 'Administrator', ownerOnlyAccess: 'Access granted by the site owner', staffLoginNote: 'Teachers and administrators cannot choose their own role during registration. Sign in with an account that the site owner has promoted.', newPassword: 'New password', confirmPassword: 'Confirm password', confirmNewPassword: 'Confirm new password', showPassword: 'Show password', hidePassword: 'Hide password', registerEmail: 'Register by email', sendResetLink: 'Send reset link', saveNewPassword: 'Save new password', alreadyRegistered: 'Already have an account? Sign in', noAccount: 'No account yet? Register', authNotConfigured: 'Online accounts are still being configured for this preview.', accountCreated: 'Account created. Open your email and verify it before signing in.', emailConfirmed: 'Email confirmed successfully. You can sign in now.', emailConfirmationFailed: 'Unable to confirm this email. The link may have expired; register again or request a new link.', resetSent: 'A password-reset link has been sent to your email.', passwordMismatch: 'The two passwords do not match.', passwordChanged: 'Password changed. You can now sign in with the new password.', authFailed: 'Unable to complete the request. Please try again.', itemUnit: 'items', newLabel: 'New', teacherInitial: 'T',
    accountManagement: 'Account management', accountManagementDescription: 'View students and grant teacher or administrator access.', accessPolicyTitle: 'How role accounts are created', accessPolicyText: 'Everyone registers by email as a student. The site owner verifies the person and promotes the account here.', searchAccount: 'Search by name or email', allRoles: 'All roles', role: 'Role', status: 'Status', createdAt: 'Created', actions: 'Actions', roleStudent: 'Student', roleTeacher: 'Teacher', roleAdmin: 'Administrator', roleOwner: 'Site owner', active: 'Active', locked: 'Locked', lockAccount: 'Lock', unlockAccount: 'Unlock', ownerProtected: 'The site-owner account is protected', accessUpdated: 'Account access updated.', accessUpdateFailed: 'Unable to update account access.', accountsLoadFailed: 'Unable to load accounts.', noAccounts: 'No matching accounts found.', previewLabel: 'Preview',
  },
  zh: {
    interfaceLanguage: '界面语言', brandShort: '学中文', brandTitle: 'LiuLiuLiu学中文',
    overview: '总览', lessons: '课程', vocabulary: '生词', vocabularyPracticeResults: '生词练习', flashcards: '抽认卡', listening: '听力', shadowing: '跟读', writing: '写作', progress: '学习进度', settings: '设置', grammar: '语法', dialogues: '课文', exercises: '练习', signOut: '退出登录', continueLesson: '继续第一课', reviewToday: '今日复习', recentProgress: '最近进度', newFeedback: '新反馈', content: '内容管理', students: '账户管理', grading: '批改作业', reports: '问题反馈', analytics: '统计', admin: '管理员', teacher: '教师', submit: '提交批改', practice: '自主练习', saveDraft: '保存草稿', answer: '答案', showAnswer: '查看答案', hideAnswer: '隐藏答案', source: '内容来源', pronunciation: '语音', profile: '账户', notifications: '通知', home: '首页', review: '复习', login: '登录', register: '注册', forgotPassword: '忘记密码', displayName: '显示名称', password: '密码', email: '电子邮箱', emailVerification: '请先验证邮箱，然后再登录。',
    landingHeroTitle: '循序渐进学中文，练习之后有反馈。', landingHeroDescription: 'LiuLiuLiu学生专属的在线学习空间：依据教材学习、每天练习，并直接获得教师评语。', startLearning: '开始学习', haveAccount: '我已有账户', trustLine: '邮箱账户 · 多设备同步 · 仅限联网使用', lessonOne: '第一课', helloMeaning: '你好 · Hello', roadmapLabel: '十五课学习路线', lessonsReady: '十五课均可学习', learningFeatures: '学习功能', featureLessonsTitle: '十五课循序学习', featureLessonsText: '生词、语法、课文和练习都安排在清晰的学习路线中。', featureAudioTitle: '使用官方音频', featureAudioText: '使用教材配套音频练习听力和课文。', featureReviewTitle: '按时复习', featureReviewText: '将生词标记为“没记住”“较难”或“已记住”，系统会安排复习。', featureSubmitTitle: '自主练习并提交', featureSubmitText: '录音和写作可以反复练习；每项正式作业只能提交一次，由教师批改。', setupNote: '源代码已准备完成；预览环境正在连接 Supabase。',
    publicHome: '网站介绍', accountName: 'LiuLiuLiu账户', registerStudentTitle: '注册学生账户', resetPasswordTitle: '重置密码', choosePasswordTitle: '设置新密码', welcomeTitle: '欢迎回来', registerDescription: '学生使用邮箱注册，验证邮箱后即可开始学习。', resetDescription: '新密码至少需要8个字符。', loginDescription: '学生、教师和管理员均在此页面登录。', studentRegistration: '学生', selfRegister: '使用邮箱自行注册', teacherAccount: '教师', ownerGrantsAccess: '由网站所有者授权', adminAccount: '管理员', ownerOnlyAccess: '由网站所有者授权', staffLoginNote: '教师和管理员注册时不能自行选择角色，请使用网站所有者已授权的账户登录。', newPassword: '新密码', confirmPassword: '确认密码', confirmNewPassword: '再次输入新密码', showPassword: '显示密码', hidePassword: '隐藏密码', registerEmail: '使用邮箱注册', sendResetLink: '发送重置链接', saveNewPassword: '保存新密码', alreadyRegistered: '已有账户？登录', noAccount: '还没有账户？注册', authNotConfigured: '预览环境的在线账户功能仍在配置中。', accountCreated: '账户已创建，请打开邮箱完成验证后再登录。', emailConfirmed: '邮箱验证成功，您现在可以登录。', emailConfirmationFailed: '无法验证此邮箱。链接可能已过期，请重新注册或申请新的验证链接。', resetSent: '密码重置链接已发送到您的邮箱。', passwordMismatch: '两次输入的密码不一致。', passwordChanged: '密码已修改，您可以使用新密码登录。', authFailed: '无法完成此操作，请重试。', itemUnit: '项', newLabel: '新', teacherInitial: '师',
    accountManagement: '账户管理', accountManagementDescription: '查看学生账户，并授予教师或管理员权限。', accessPolicyTitle: '不同角色的账户如何创建', accessPolicyText: '所有人先使用邮箱注册为学生。网站所有者核实身份后，在本页面提升账户权限。', searchAccount: '按姓名或邮箱搜索', allRoles: '全部角色', role: '角色', status: '状态', createdAt: '注册时间', actions: '操作', roleStudent: '学生', roleTeacher: '教师', roleAdmin: '管理员', roleOwner: '网站所有者', active: '正常', locked: '已锁定', lockAccount: '锁定', unlockAccount: '解锁', ownerProtected: '网站所有者账户受保护', accessUpdated: '账户权限已更新。', accessUpdateFailed: '无法更新账户权限。', accountsLoadFailed: '无法加载账户列表。', noAccounts: '没有找到符合条件的账户。', previewLabel: '预览',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children, initialLanguage = 'vi' }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('liuliuliu-language') || initialLanguage)

  useEffect(() => {
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : language
    document.title = translations[language]?.brandTitle || translations.vi.brandTitle
    localStorage.setItem('liuliuliu-language', language)
  }, [language])

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] || translations.vi[key] || key,
    l: (vi, en, zh) => language === 'en' ? en : language === 'zh' ? zh : vi,
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}
