WebSocket server error:
Error: listen EPERM: operation not permitted 0.0.0.0:24678
    at Server.setupListenHandle [as _listen2] (node:net:2145:21)
    at listenInCluster (node:net:2224:12)
    at Server.listen (node:net:2344:7)
    at Object.listen (file:///Users/fanzhuan/.codex/.chatgpt-projects/g-p-6a65699d9bd48191b3e2ea4940c34275/website/node_modules/.pnpm/vite@8.2.1/node_modules/vite/dist/node/chunks/node.js:17633:18)
    at Object.listen (file:///Users/fanzhuan/.codex/.chatgpt-projects/g-p-6a65699d9bd48191b3e2ea4940c34275/website/node_modules/.pnpm/vite@8.2.1/node_modules/vite/dist/node/chunks/node.js:26894:27)
    at DevEnvironment.listen (file:///Users/fanzhuan/.codex/.chatgpt-projects/g-p-6a65699d9bd48191b3e2ea4940c34275/website/node_modules/.pnpm/vite@8.2.1/node_modules/vite/dist/node/chunks/node.js:35445:12)
    at file:///Users/fanzhuan/.codex/.chatgpt-projects/g-p-6a65699d9bd48191b3e2ea4940c34275/website/node_modules/.pnpm/vite@8.2.1/node_modules/vite/dist/node/chunks/node.js:26598:95
    at Array.map (<anonymous>)
    at file:///Users/fanzhuan/.codex/.chatgpt-projects/g-p-6a65699d9bd48191b3e2ea4940c34275/website/node_modules/.pnpm/vite@8.2.1/node_modules/vite/dist/node/chunks/node.js:26598:82
    at async _createServer (file:///Users/fanzhuan/.codex/.chatgpt-projects/g-p-6a65699d9bd48191b3e2ea4940c34275/website/node_modules/.pnpm/vite@8.2.1/node_modules/vite/dist/node/chunks/node.js:26615:9)
begin;

insert into public.lessons (id, course_id, lesson_number, title_zh, pinyin, title_vi, title_en, objectives, source_coverage, status, published_at)
values
('hsk1-lesson-02', 'hsk1', 2, '我叫李文', 'Wǒ jiào Lǐ Wén', 'Tôi tên là Lý Văn', 'My name is Li Wen', '[{"vi":"Tự giới thiệu và hỏi tên người khác.","en":"Tự giới thiệu và hỏi tên người khác.","zh":"Tự giới thiệu và hỏi tên người khác."},{"vi":"Xin lỗi và đáp lời xin lỗi.","en":"Xin lỗi và đáp lời xin lỗi.","zh":"Xin lỗi và đáp lời xin lỗi."},{"vi":"Nắm trật tự câu cơ bản và cấu trúc tên tiếng Trung.","en":"Nắm trật tự câu cơ bản và cấu trúc tên tiếng Trung.","zh":"Nắm trật tự câu cơ bản và cấu trúc tên tiếng Trung."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 2","audio":"Audio giáo trình và sách bài tập Bài 2"}'::jsonb, 'published', now()),
('hsk1-lesson-03', 'hsk1', 3, '我是中国人', 'Wǒ shì Zhōngguó rén', 'Tôi là người Trung Quốc', 'I am Chinese', '[{"vi":"Giới thiệu quốc tịch và nghề nghiệp.","en":"Giới thiệu quốc tịch và nghề nghiệp.","zh":"Giới thiệu quốc tịch và nghề nghiệp."},{"vi":"Dùng trợ từ kết cấu “的”.","en":"Dùng trợ từ kết cấu “的”.","zh":"Dùng trợ từ kết cấu “的”."},{"vi":"Đặt câu hỏi đúng–sai với “吗”.","en":"Đặt câu hỏi đúng–sai với “吗”.","zh":"Đặt câu hỏi đúng–sai với “吗”."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 3","audio":"Audio giáo trình và sách bài tập Bài 3"}'::jsonb, 'published', now()),
('hsk1-lesson-04', 'hsk1', 4, '我有两个孩子', 'Wǒ yǒu liǎng ge háizi', 'Tôi có hai người con', 'I have two children', '[{"vi":"Nói về gia đình bằng câu chữ “有”.","en":"Nói về gia đình bằng câu chữ “有”.","zh":"Nói về gia đình bằng câu chữ “有”."},{"vi":"Dùng mẫu “A……，B呢？”.","en":"Dùng mẫu “A……，B呢？”.","zh":"Dùng mẫu “A……，B呢？”."},{"vi":"Dùng số từ, lượng từ và hỏi tuổi.","en":"Dùng số từ, lượng từ và hỏi tuổi.","zh":"Dùng số từ, lượng từ và hỏi tuổi."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 4","audio":"Audio giáo trình và sách bài tập Bài 4"}'::jsonb, 'published', now()),
('hsk1-lesson-05', 'hsk1', 5, '今天我休息', 'Jīntiān wǒ xiūxi', 'Hôm nay tôi nghỉ', 'I am off today', '[{"vi":"Nói ngày tháng và thứ trong tuần.","en":"Nói ngày tháng và thứ trong tuần.","zh":"Nói ngày tháng và thứ trong tuần."},{"vi":"Dùng động từ năng nguyện “会”.","en":"Dùng động từ năng nguyện “会”.","zh":"Dùng động từ năng nguyện “会”."},{"vi":"Hiểu câu vị ngữ danh từ.","en":"Hiểu câu vị ngữ danh từ.","zh":"Hiểu câu vị ngữ danh từ."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 5","audio":"Audio giáo trình và sách bài tập Bài 5"}'::jsonb, 'published', now()),
('hsk1-lesson-06', 'hsk1', 6, '你的手机号是多少？', 'Nǐ de shǒujī hào shì duōshao?', 'Số điện thoại di động của bạn là bao nhiêu?', 'What is your mobile number?', '[{"vi":"Hỏi và đọc số điện thoại.","en":"Hỏi và đọc số điện thoại.","zh":"Hỏi và đọc số điện thoại."},{"vi":"Dùng câu liên động để nói mục đích và cách thức.","en":"Dùng câu liên động để nói mục đích và cách thức.","zh":"Dùng câu liên động để nói mục đích và cách thức."},{"vi":"Dùng “想” và “怎么”.","en":"Dùng “想” và “怎么”.","zh":"Dùng “想” và “怎么”."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 6","audio":"Audio giáo trình và sách bài tập Bài 6"}'::jsonb, 'published', now()),
('hsk1-lesson-07', 'hsk1', 7, '我晚上六点半下班', 'Wǒ wǎnshang liù diǎn bàn xiàbān', 'Tôi tan làm lúc 6 giờ 30 tối', 'I finish work at 6:30 p.m.', '[{"vi":"Nói thời gian diễn ra sự việc.","en":"Nói thời gian diễn ra sự việc.","zh":"Nói thời gian diễn ra sự việc."},{"vi":"Dùng “吧” để đề nghị.","en":"Dùng “吧” để đề nghị.","zh":"Dùng “吧” để đề nghị."},{"vi":"Dùng “呢” và đặt từ chỉ thời gian đúng vị trí.","en":"Dùng “呢” và đặt từ chỉ thời gian đúng vị trí.","zh":"Dùng “呢” và đặt từ chỉ thời gian đúng vị trí."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 7","audio":"Audio giáo trình và sách bài tập Bài 7"}'::jsonb, 'published', now()),
('hsk1-lesson-08', 'hsk1', 8, '我爸爸也在医院工作', 'Wǒ bàba yě zài yīyuàn gōngzuò', 'Bố tôi cũng làm việc ở bệnh viện', 'My father also works at a hospital', '[{"vi":"Mô tả vị trí và nơi chốn.","en":"Mô tả vị trí và nơi chốn.","zh":"Mô tả vị trí và nơi chốn."},{"vi":"Dùng giới từ “在”.","en":"Dùng giới từ “在”.","zh":"Dùng giới từ “在”."},{"vi":"Dùng động từ năng nguyện “能”.","en":"Dùng động từ năng nguyện “能”.","zh":"Dùng động từ năng nguyện “能”."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 8","audio":"Audio giáo trình và sách bài tập Bài 8"}'::jsonb, 'published', now()),
('hsk1-lesson-09', 'hsk1', 9, '我明天上午在学校学习', 'Wǒ míngtiān shàngwǔ zài xuéxiào xuéxí', 'Sáng mai tôi học ở trường', 'I will study at school tomorrow morning', '[{"vi":"Dùng câu tồn hiện cơ bản.","en":"Dùng câu tồn hiện cơ bản.","zh":"Dùng câu tồn hiện cơ bản."},{"vi":"Sắp xếp đúng từ chỉ thời gian và nơi chốn.","en":"Sắp xếp đúng từ chỉ thời gian và nơi chốn.","zh":"Sắp xếp đúng từ chỉ thời gian và nơi chốn."},{"vi":"Dùng “第” để biểu thị thứ tự.","en":"Dùng “第” để biểu thị thứ tự.","zh":"Dùng “第” để biểu thị thứ tự."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 9","audio":"Audio giáo trình và sách bài tập Bài 9"}'::jsonb, 'published', now()),
('hsk1-lesson-10', 'hsk1', 10, '这儿的苹果真便宜！', 'Zhèr de píngguǒ zhēn piányi!', 'Táo ở đây thật rẻ!', 'The apples here are really cheap!', '[{"vi":"Hỏi và trả lời giá tiền.","en":"Hỏi và trả lời giá tiền.","zh":"Hỏi và trả lời giá tiền."},{"vi":"Dùng câu vị ngữ tính từ.","en":"Dùng câu vị ngữ tính từ.","zh":"Dùng câu vị ngữ tính từ."},{"vi":"Hỏi nhận xét với “怎么样”.","en":"Hỏi nhận xét với “怎么样”.","zh":"Hỏi nhận xét với “怎么样”."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 10","audio":"Audio giáo trình và sách bài tập Bài 10"}'::jsonb, 'published', now()),
('hsk1-lesson-11', 'hsk1', 11, '我读大学呢', 'Wǒ dú dàxué ne', 'Tôi đang học đại học', 'I am studying at university', '[{"vi":"Nói hành động đang diễn ra.","en":"Nói hành động đang diễn ra.","zh":"Nói hành động đang diễn ra."},{"vi":"Đặt câu hỏi chính phản với dạng A-không-A.","en":"Đặt câu hỏi chính phản với dạng A-không-A.","zh":"Đặt câu hỏi chính phản với dạng A-không-A."},{"vi":"Dùng “要” để nói dự định.","en":"Dùng “要” để nói dự định.","zh":"Dùng “要” để nói dự định."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 11","audio":"Audio giáo trình và sách bài tập Bài 11"}'::jsonb, 'published', now()),
('hsk1-lesson-12', 'hsk1', 12, '昨天下雪了', 'Zuótiān xià xuě le', 'Hôm qua tuyết đã rơi', 'It snowed yesterday', '[{"vi":"Nói về thời tiết và tình trạng sức khỏe.","en":"Nói về thời tiết và tình trạng sức khỏe.","zh":"Nói về thời tiết và tình trạng sức khỏe."},{"vi":"Dùng “了” để biểu thị thay đổi.","en":"Dùng “了” để biểu thị thay đổi.","zh":"Dùng “了” để biểu thị thay đổi."},{"vi":"Dùng cấu trúc “太……了”.","en":"Dùng cấu trúc “太……了”.","zh":"Dùng cấu trúc “太……了”."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 12","audio":"Audio giáo trình và sách bài tập Bài 12"}'::jsonb, 'published', now()),
('hsk1-lesson-13', 'hsk1', 13, '请给我一杯茶', 'Qǐng gěi wǒ yì bēi chá', 'Cho tôi một tách trà', 'Please give me a cup of tea', '[{"vi":"Gọi món và yêu cầu phục vụ lịch sự.","en":"Gọi món và yêu cầu phục vụ lịch sự.","zh":"Gọi món và yêu cầu phục vụ lịch sự."},{"vi":"Dùng câu hai tân ngữ.","en":"Dùng câu hai tân ngữ.","zh":"Dùng câu hai tân ngữ."},{"vi":"Dùng “可以” và động từ + “一下”.","en":"Dùng “可以” và động từ + “一下”.","zh":"Dùng “可以” và động từ + “一下”."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 13","audio":"Audio giáo trình và sách bài tập Bài 13"}'::jsonb, 'published', now()),
('hsk1-lesson-14', 'hsk1', 14, '我看了一个电影', 'Wǒ kàn le yí ge diànyǐng', 'Tôi đã xem một bộ phim', 'I watched a film', '[{"vi":"Dùng “了” sau động từ để nói hành động đã hoàn thành.","en":"Dùng “了” sau động từ để nói hành động đã hoàn thành.","zh":"Dùng “了” sau động từ để nói hành động đã hoàn thành."},{"vi":"Dùng phó từ “都”.","en":"Dùng phó từ “都”.","zh":"Dùng phó từ “都”."},{"vi":"Nhận biết động từ li hợp.","en":"Nhận biết động từ li hợp.","zh":"Nhận biết động từ li hợp."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 14","audio":"Audio giáo trình và sách bài tập Bài 14"}'::jsonb, 'published', now()),
('hsk1-lesson-15', 'hsk1', 15, '大兴机场见！', 'Dàxīng Jīchǎng jiàn!', 'Hẹn gặp ở Sân bay Đại Hưng!', 'See you at Daxing Airport!', '[{"vi":"Nói kế hoạch du lịch và thời gian di chuyển.","en":"Nói kế hoạch du lịch và thời gian di chuyển.","zh":"Nói kế hoạch du lịch và thời gian di chuyển."},{"vi":"Dùng câu ghép với “还/也”.","en":"Dùng câu ghép với “还/也”.","zh":"Dùng câu ghép với “还/也”."},{"vi":"Vận dụng phép lịch sự khi đón tiếp khách.","en":"Vận dụng phép lịch sự khi đón tiếp khách.","zh":"Vận dụng phép lịch sự khi đón tiếp khách."}]'::jsonb, '{"pptSlides":"PPT tiếng Việt Bài 15","audio":"Audio giáo trình và sách bài tập Bài 15"}'::jsonb, 'published', now())
on conflict (id) do update set
  title_zh = excluded.title_zh,
  pinyin = excluded.pinyin,
  title_vi = excluded.title_vi,
  title_en = excluded.title_en,
  objectives = excluded.objectives,
  source_coverage = excluded.source_coverage,
  status = excluded.status,
  published_at = coalesce(public.lessons.published_at, excluded.published_at);


insert into public.vocabulary (id, lesson_id, hanzi, pinyin, han_viet, part_of_speech_vi, part_of_speech_en, meaning_vi, meaning_en, source_note, sort_order, status)
values
('hsk1-lesson-02-v-w-01', 'hsk1-lesson-02', '请问', 'qǐngwèn', null, 'công thức lịch sự', null, 'xin hỏi; cho tôi hỏi', 'excuse me; may I ask', 'PPT Bài 2 · Từ mới', 1, 'published'),
('hsk1-lesson-02-v-w-02', 'hsk1-lesson-02', '你', 'nǐ', null, 'đại từ', null, 'bạn', 'you', 'PPT Bài 2 · Từ mới', 2, 'published'),
('hsk1-lesson-02-v-w-03', 'hsk1-lesson-02', '叫', 'jiào', null, 'động từ', null, 'tên là; gọi', 'to be called; to call', 'PPT Bài 2 · Từ mới', 3, 'published'),
('hsk1-lesson-02-v-w-04', 'hsk1-lesson-02', '什么', 'shénme', null, 'đại từ nghi vấn', null, 'gì', 'what', 'PPT Bài 2 · Từ mới', 4, 'published'),
('hsk1-lesson-02-v-w-05', 'hsk1-lesson-02', '名字', 'míngzi', null, 'danh từ', null, 'tên', 'name', 'PPT Bài 2 · Từ mới', 5, 'published'),
('hsk1-lesson-02-v-w-06', 'hsk1-lesson-02', '我', 'wǒ', null, 'đại từ', null, 'tôi', 'I; me', 'PPT Bài 2 · Từ mới', 6, 'published'),
('hsk1-lesson-02-v-w-07', 'hsk1-lesson-02', '不', 'bù', null, 'phó từ', null, 'không', 'not', 'PPT Bài 2 · Từ mới', 7, 'published'),
('hsk1-lesson-02-v-w-08', 'hsk1-lesson-02', '是', 'shì', null, 'động từ', null, 'là', 'to be', 'PPT Bài 2 · Từ mới', 8, 'published'),
('hsk1-lesson-02-v-w-09', 'hsk1-lesson-02', '对不起', 'duìbuqǐ', null, 'công thức giao tiếp', null, 'xin lỗi', 'sorry', 'PPT Bài 2 · Từ mới', 9, 'published'),
('hsk1-lesson-02-v-w-10', 'hsk1-lesson-02', '没关系', 'méi guānxi', null, 'công thức giao tiếp', null, 'không sao', 'it does not matter', 'PPT Bài 2 · Từ mới', 10, 'published'),
('hsk1-lesson-02-v-w-11', 'hsk1-lesson-02', '没事', 'méishì', null, 'công thức giao tiếp', null, 'không sao; không có việc gì', 'it is fine; nothing', 'PPT Bài 2 · Từ mới', 11, 'published'),
('hsk1-lesson-02-v-w-12', 'hsk1-lesson-02', '很', 'hěn', null, 'phó từ', null, 'rất', 'very', 'PPT Bài 2 · Từ mới', 12, 'published'),
('hsk1-lesson-02-v-w-13', 'hsk1-lesson-02', '高兴', 'gāoxìng', null, 'tính từ', null, 'vui mừng', 'happy; glad', 'PPT Bài 2 · Từ mới', 13, 'published'),
('hsk1-lesson-02-v-w-14', 'hsk1-lesson-02', '认识', 'rènshi', null, 'động từ', null, 'quen biết; làm quen', 'to know; to meet', 'PPT Bài 2 · Từ mới', 14, 'published'),
('hsk1-lesson-02-v-w-15', 'hsk1-lesson-02', '也', 'yě', null, 'phó từ', null, 'cũng', 'also', 'PPT Bài 2 · Từ mới', 15, 'published'),
('hsk1-lesson-03-v-w-01', 'hsk1-lesson-03', '人', 'rén', null, 'danh từ', null, 'người', 'person', 'PPT Bài 3 · Từ mới', 1, 'published'),
('hsk1-lesson-03-v-w-02', 'hsk1-lesson-03', '的', 'de', null, 'trợ từ', null, 'trợ từ kết cấu đứng sau thành phần bổ nghĩa', 'structural particle after a modifier', 'PPT Bài 3 · Từ mới', 2, 'published'),
('hsk1-lesson-03-v-w-03', 'hsk1-lesson-03', '中国', 'Zhōngguó', null, 'danh từ riêng', null, 'Trung Quốc', 'China', 'PPT Bài 3 · Từ mới', 3, 'published'),
('hsk1-lesson-03-v-w-04', 'hsk1-lesson-03', '法国', 'Fǎguó', null, 'danh từ riêng', null, 'Pháp', 'France', 'PPT Bài 3 · Từ mới', 4, 'published'),
('hsk1-lesson-03-v-w-05', 'hsk1-lesson-03', '中文', 'Zhōngwén', null, 'danh từ', null, 'tiếng Trung', 'Chinese language', 'PPT Bài 3 · Từ mới', 5, 'published'),
('hsk1-lesson-03-v-w-06', 'hsk1-lesson-03', '她', 'tā', null, 'đại từ', null, 'cô ấy', 'she; her', 'PPT Bài 3 · Từ mới', 6, 'published'),
('hsk1-lesson-03-v-w-07', 'hsk1-lesson-03', '这', 'zhè', null, 'đại từ', null, 'đây; này', 'this', 'PPT Bài 3 · Từ mới', 7, 'published'),
('hsk1-lesson-03-v-w-08', 'hsk1-lesson-03', '谁', 'shéi', null, 'đại từ nghi vấn', null, 'ai', 'who', 'PPT Bài 3 · Từ mới', 8, 'published'),
('hsk1-lesson-03-v-w-09', 'hsk1-lesson-03', '女朋友', 'nǚpéngyou', null, 'danh từ', null, 'bạn gái', 'girlfriend', 'PPT Bài 3 · Từ mới', 9, 'published'),
('hsk1-lesson-03-v-w-10', 'hsk1-lesson-03', '哪', 'nǎ', null, 'đại từ nghi vấn', null, 'nào', 'which', 'PPT Bài 3 · Từ mới', 10, 'published'),
('hsk1-lesson-03-v-w-11', 'hsk1-lesson-03', '国', 'guó', null, 'danh từ', null, 'nước; quốc gia', 'country', 'PPT Bài 3 · Từ mới', 11, 'published'),
('hsk1-lesson-03-v-w-12', 'hsk1-lesson-03', '泰国', 'Tàiguó', null, 'danh từ riêng', null, 'Thái Lan', 'Thailand', 'PPT Bài 3 · Từ mới', 12, 'published'),
('hsk1-lesson-03-v-w-13', 'hsk1-lesson-03', '喂', 'wèi', null, 'thán từ', null, 'a-lô; này', 'hello on the phone; hey', 'PPT Bài 3 · Từ mới', 13, 'published'),
('hsk1-lesson-03-v-w-14', 'hsk1-lesson-03', '姐姐', 'jiějie', null, 'danh từ', null, 'chị gái', 'older sister', 'PPT Bài 3 · Từ mới', 14, 'published'),
('hsk1-lesson-03-v-w-15', 'hsk1-lesson-03', '工作', 'gōngzuò', null, 'danh từ / động từ', null, 'công việc; làm việc', 'work; to work', 'PPT Bài 3 · Từ mới', 15, 'published'),
('hsk1-lesson-03-v-w-16', 'hsk1-lesson-03', '还', 'hái', null, 'phó từ', null, 'vẫn; còn', 'still; also', 'PPT Bài 3 · Từ mới', 16, 'published'),
('hsk1-lesson-03-v-w-17', 'hsk1-lesson-03', '忙', 'máng', null, 'tính từ', null, 'bận', 'busy', 'PPT Bài 3 · Từ mới', 17, 'published'),
('hsk1-lesson-03-v-w-18', 'hsk1-lesson-03', '吗', 'ma', null, 'trợ từ', null, 'trợ từ nghi vấn', 'question particle', 'PPT Bài 3 · Từ mới', 18, 'published'),
('hsk1-lesson-03-v-w-19', 'hsk1-lesson-03', '对', 'duì', null, 'tính từ', null, 'đúng', 'correct; right', 'PPT Bài 3 · Từ mới', 19, 'published'),
('hsk1-lesson-03-v-w-20', 'hsk1-lesson-03', '太', 'tài', null, 'phó từ', null, 'quá', 'too; extremely', 'PPT Bài 3 · Từ mới', 20, 'published'),
('hsk1-lesson-03-v-w-21', 'hsk1-lesson-03', '我们', 'wǒmen', null, 'đại từ', null, 'chúng tôi; chúng ta', 'we; us', 'PPT Bài 3 · Từ mới', 21, 'published'),
('hsk1-lesson-03-v-w-22', 'hsk1-lesson-03', '想', 'xiǎng', null, 'động từ', null, 'nhớ; muốn', 'to miss; to want', 'PPT Bài 3 · Từ mới', 22, 'published'),
('hsk1-lesson-04-v-w-01', 'hsk1-lesson-04', '有', 'yǒu', null, 'động từ', null, 'có', 'to have', 'PPT Bài 4 · Từ mới', 1, 'published'),
('hsk1-lesson-04-v-w-02', 'hsk1-lesson-04', '多少', 'duōshao', null, 'đại từ nghi vấn', null, 'bao nhiêu', 'how many; how much', 'PPT Bài 4 · Từ mới', 2, 'published'),
('hsk1-lesson-04-v-w-03', 'hsk1-lesson-04', '个', 'ge', null, 'lượng từ', null, 'lượng từ thông dụng', 'general measure word', 'PPT Bài 4 · Từ mới', 3, 'published'),
('hsk1-lesson-04-v-w-04', 'hsk1-lesson-04', '哥哥', 'gēge', null, 'danh từ', null, 'anh trai', 'older brother', 'PPT Bài 4 · Từ mới', 4, 'published'),
('hsk1-lesson-04-v-w-05', 'hsk1-lesson-04', '呢', 'ne', null, 'trợ từ', null, 'thế còn…; trợ từ', 'and what about; particle', 'PPT Bài 4 · Từ mới', 5, 'published'),
('hsk1-lesson-04-v-w-06', 'hsk1-lesson-04', '没有', 'méiyǒu', null, 'động từ', null, 'không có', 'not have; there is not', 'PPT Bài 4 · Từ mới', 6, 'published'),
('hsk1-lesson-04-v-w-07', 'hsk1-lesson-04', '家', 'jiā', null, 'danh từ', null, 'gia đình; nhà', 'family; home', 'PPT Bài 4 · Từ mới', 7, 'published'),
('hsk1-lesson-04-v-w-08', 'hsk1-lesson-04', '几', 'jǐ', null, 'đại từ nghi vấn', null, 'mấy; bao nhiêu', 'how many; several', 'PPT Bài 4 · Từ mới', 8, 'published'),
('hsk1-lesson-04-v-w-09', 'hsk1-lesson-04', '口', 'kǒu', null, 'lượng từ', null, 'lượng từ chỉ người trong gia đình', 'measure word for family members', 'PPT Bài 4 · Từ mới', 9, 'published'),
('hsk1-lesson-04-v-w-10', 'hsk1-lesson-04', '爸爸', 'bàba', null, 'danh từ', null, 'bố', 'father', 'PPT Bài 4 · Từ mới', 10, 'published'),
('hsk1-lesson-04-v-w-11', 'hsk1-lesson-04', '妈妈', 'māma', null, 'danh từ', null, 'mẹ', 'mother', 'PPT Bài 4 · Từ mới', 11, 'published'),
('hsk1-lesson-04-v-w-12', 'hsk1-lesson-04', '妹妹', 'mèimei', null, 'danh từ', null, 'em gái', 'younger sister', 'PPT Bài 4 · Từ mới', 12, 'published'),
('hsk1-lesson-04-v-w-13', 'hsk1-lesson-04', '和', 'hé', null, 'liên từ', null, 'và', 'and', 'PPT Bài 4 · Từ mới', 13, 'published'),
('hsk1-lesson-04-v-w-14', 'hsk1-lesson-04', '儿子', 'érzi', null, 'danh từ', null, 'con trai', 'son', 'PPT Bài 4 · Từ mới', 14, 'published'),
('hsk1-lesson-04-v-w-15', 'hsk1-lesson-04', '孩子', 'háizi', null, 'danh từ', null, 'con; trẻ em', 'child', 'PPT Bài 4 · Từ mới', 15, 'published'),
('hsk1-lesson-04-v-w-16', 'hsk1-lesson-04', '女儿', 'nǚ’ér', null, 'danh từ', null, 'con gái', 'daughter', 'PPT Bài 4 · Từ mới', 16, 'published'),
('hsk1-lesson-04-v-w-17', 'hsk1-lesson-04', '岁', 'suì', null, 'lượng từ', null, 'tuổi', 'years old', 'PPT Bài 4 · Từ mới', 17, 'published'),
('hsk1-lesson-04-v-w-18', 'hsk1-lesson-04', '他', 'tā', null, 'đại từ', null, 'anh ấy; ông ấy', 'he; him', 'PPT Bài 4 · Từ mới', 18, 'published'),
('hsk1-lesson-04-v-w-19', 'hsk1-lesson-04', '今年', 'jīnnián', null, 'danh từ thời gian', null, 'năm nay', 'this year', 'PPT Bài 4 · Từ mới', 19, 'published'),
('hsk1-lesson-04-v-w-20', 'hsk1-lesson-04', '多', 'duō', null, 'đại từ / tính từ', null, 'bao nhiêu; nhiều', 'how; many', 'PPT Bài 4 · Từ mới', 20, 'published'),
('hsk1-lesson-04-v-w-21', 'hsk1-lesson-04', '大', 'dà', null, 'tính từ', null, 'lớn; bao nhiêu tuổi', 'big; old', 'PPT Bài 4 · Từ mới', 21, 'published'),
('hsk1-lesson-05-v-w-01', 'hsk1-lesson-05', '今天', 'jīntiān', null, 'danh từ thời gian', null, 'hôm nay', 'today', 'PPT Bài 5 · Từ mới', 1, 'published'),
('hsk1-lesson-05-v-w-02', 'hsk1-lesson-05', '号', 'hào', null, 'danh từ', null, 'ngày; số', 'date; number', 'PPT Bài 5 · Từ mới', 2, 'published'),
('hsk1-lesson-05-v-w-03', 'hsk1-lesson-05', '月', 'yuè', null, 'danh từ', null, 'tháng', 'month', 'PPT Bài 5 · Từ mới', 3, 'published'),
('hsk1-lesson-05-v-w-04', 'hsk1-lesson-05', '日', 'rì', null, 'danh từ', null, 'ngày', 'day; date', 'PPT Bài 5 · Từ mới', 4, 'published'),
('hsk1-lesson-05-v-w-05', 'hsk1-lesson-05', '星期', 'xīngqī', null, 'danh từ', null, 'tuần; thứ', 'week; weekday', 'PPT Bài 5 · Từ mới', 5, 'published'),
('hsk1-lesson-05-v-w-06', 'hsk1-lesson-05', '星期日', 'Xīngqīrì', null, 'danh từ', null, 'Chủ nhật', 'Sunday', 'PPT Bài 5 · Từ mới', 6, 'published'),
('hsk1-lesson-05-v-w-07', 'hsk1-lesson-05', '星期天', 'Xīngqītiān', null, 'danh từ', null, 'Chủ nhật', 'Sunday', 'PPT Bài 5 · Từ mới', 7, 'published'),
('hsk1-lesson-05-v-w-08', 'hsk1-lesson-05', '休息', 'xiūxi', null, 'động từ', null, 'nghỉ ngơi', 'to rest', 'PPT Bài 5 · Từ mới', 8, 'published'),
('hsk1-lesson-05-v-w-09', 'hsk1-lesson-05', '会', 'huì', null, 'động từ năng nguyện', null, 'biết; có thể do học được', 'can; know how to', 'PPT Bài 5 · Từ mới', 9, 'published'),
('hsk1-lesson-05-v-w-10', 'hsk1-lesson-05', '做饭', 'zuòfàn', null, 'động từ', null, 'nấu ăn', 'to cook', 'PPT Bài 5 · Từ mới', 10, 'published'),
('hsk1-lesson-05-v-w-11', 'hsk1-lesson-05', '做', 'zuò', null, 'động từ', null, 'làm', 'to do; to make', 'PPT Bài 5 · Từ mới', 11, 'published'),
('hsk1-lesson-05-v-w-12', 'hsk1-lesson-05', '面条儿', 'miàntiáor', null, 'danh từ', null, 'mì sợi', 'noodles', 'PPT Bài 5 · Từ mới', 12, 'published'),
('hsk1-lesson-05-v-w-13', 'hsk1-lesson-05', '饺子', 'jiǎozi', null, 'danh từ', null, 'sủi cảo', 'dumplings', 'PPT Bài 5 · Từ mới', 13, 'published'),
('hsk1-lesson-05-v-w-14', 'hsk1-lesson-05', '一些', 'yìxiē', null, 'số lượng từ', null, 'một ít; một số', 'some', 'PPT Bài 5 · Từ mới', 14, 'published'),
('hsk1-lesson-05-v-w-15', 'hsk1-lesson-05', '菜', 'cài', null, 'danh từ', null, 'món ăn; rau', 'dish; vegetable', 'PPT Bài 5 · Từ mới', 15, 'published'),
('hsk1-lesson-05-v-w-16', 'hsk1-lesson-05', '下班', 'xiàbān', null, 'động từ', null, 'tan làm', 'to get off work', 'PPT Bài 5 · Từ mới', 16, 'published'),
('hsk1-lesson-05-v-w-17', 'hsk1-lesson-05', '新', 'xīn', null, 'tính từ', null, 'mới', 'new', 'PPT Bài 5 · Từ mới', 17, 'published'),
('hsk1-lesson-05-v-w-18', 'hsk1-lesson-05', '电脑', 'diànnǎo', null, 'danh từ', null, 'máy tính', 'computer', 'PPT Bài 5 · Từ mới', 18, 'published'),
('hsk1-lesson-05-v-w-19', 'hsk1-lesson-05', '真', 'zhēn', null, 'phó từ', null, 'thật; thực sự', 'really', 'PPT Bài 5 · Từ mới', 19, 'published'),
('hsk1-lesson-05-v-w-20', 'hsk1-lesson-05', '好看', 'hǎokàn', null, 'tính từ', null, 'đẹp; dễ nhìn', 'good-looking', 'PPT Bài 5 · Từ mới', 20, 'published'),
('hsk1-lesson-05-v-w-21', 'hsk1-lesson-05', '喜欢', 'xǐhuan', null, 'động từ', null, 'thích', 'to like', 'PPT Bài 5 · Từ mới', 21, 'published'),
('hsk1-lesson-05-v-w-22', 'hsk1-lesson-05', '它', 'tā', null, 'đại từ', null, 'nó', 'it', 'PPT Bài 5 · Từ mới', 22, 'published'),
('hsk1-lesson-06-v-w-01', 'hsk1-lesson-06', '手机', 'shǒujī', null, 'danh từ', null, 'điện thoại di động', 'mobile phone', 'PPT Bài 6 · Từ mới', 1, 'published'),
('hsk1-lesson-06-v-w-02', 'hsk1-lesson-06', '电话', 'diànhuà', null, 'danh từ', null, 'điện thoại; cuộc gọi', 'telephone; phone call', 'PPT Bài 6 · Từ mới', 2, 'published'),
('hsk1-lesson-06-v-w-03', 'hsk1-lesson-06', '号', 'hào', null, 'danh từ', null, 'số', 'number', 'PPT Bài 6 · Từ mới', 3, 'published'),
('hsk1-lesson-06-v-w-04', 'hsk1-lesson-06', '明天', 'míngtiān', null, 'danh từ thời gian', null, 'ngày mai', 'tomorrow', 'PPT Bài 6 · Từ mới', 4, 'published'),
('hsk1-lesson-06-v-w-05', 'hsk1-lesson-06', '去', 'qù', null, 'động từ', null, 'đi', 'to go', 'PPT Bài 6 · Từ mới', 5, 'published'),
('hsk1-lesson-06-v-w-06', 'hsk1-lesson-06', '哪儿', 'nǎr', null, 'đại từ nghi vấn', null, 'đâu; nơi nào', 'where', 'PPT Bài 6 · Từ mới', 6, 'published'),
('hsk1-lesson-06-v-w-07', 'hsk1-lesson-06', '想', 'xiǎng', null, 'động từ năng nguyện', null, 'muốn', 'to want', 'PPT Bài 6 · Từ mới', 7, 'published'),
('hsk1-lesson-06-v-w-08', 'hsk1-lesson-06', '超市', 'chāoshì', null, 'danh từ', null, 'siêu thị', 'supermarket', 'PPT Bài 6 · Từ mới', 8, 'published'),
('hsk1-lesson-06-v-w-09', 'hsk1-lesson-06', '买', 'mǎi', null, 'động từ', null, 'mua', 'to buy', 'PPT Bài 6 · Từ mới', 9, 'published'),
('hsk1-lesson-06-v-w-10', 'hsk1-lesson-06', '东西', 'dōngxi', null, 'danh từ', null, 'đồ; vật; thứ', 'thing; stuff', 'PPT Bài 6 · Từ mới', 10, 'published'),
('hsk1-lesson-06-v-w-11', 'hsk1-lesson-06', '些', 'xiē', null, 'lượng từ', null, 'một ít; một số', 'some', 'PPT Bài 6 · Từ mới', 11, 'published'),
('hsk1-lesson-06-v-w-12', 'hsk1-lesson-06', '牛奶', 'niúnǎi', null, 'danh từ', null, 'sữa bò', 'milk', 'PPT Bài 6 · Từ mới', 12, 'published'),
('hsk1-lesson-06-v-w-13', 'hsk1-lesson-06', '吃', 'chī', null, 'động từ', null, 'ăn', 'to eat', 'PPT Bài 6 · Từ mới', 13, 'published'),
('hsk1-lesson-06-v-w-14', 'hsk1-lesson-06', '晚饭', 'wǎnfàn', null, 'danh từ', null, 'bữa tối', 'dinner', 'PPT Bài 6 · Từ mới', 14, 'published'),
('hsk1-lesson-06-v-w-15', 'hsk1-lesson-06', '那边', 'nàbiān', null, 'đại từ nơi chốn', null, 'phía bên kia; đằng kia', 'over there', 'PPT Bài 6 · Từ mới', 15, 'published'),
('hsk1-lesson-06-v-w-16', 'hsk1-lesson-06', '包子', 'bāozi', null, 'danh từ', null, 'bánh bao', 'steamed bun', 'PPT Bài 6 · Từ mới', 16, 'published'),
('hsk1-lesson-06-v-w-17', 'hsk1-lesson-06', '非常', 'fēicháng', null, 'phó từ', null, 'vô cùng; rất', 'very; extremely', 'PPT Bài 6 · Từ mới', 17, 'published'),
('hsk1-lesson-06-v-w-18', 'hsk1-lesson-06', '好吃', 'hǎochī', null, 'tính từ', null, 'ngon', 'delicious', 'PPT Bài 6 · Từ mới', 18, 'published'),
('hsk1-lesson-06-v-w-19', 'hsk1-lesson-06', '米饭', 'mǐfàn', null, 'danh từ', null, 'cơm trắng', 'cooked rice', 'PPT Bài 6 · Từ mới', 19, 'published'),
('hsk1-lesson-06-v-w-20', 'hsk1-lesson-06', '怎么', 'zěnme', null, 'đại từ nghi vấn', null, 'thế nào; bằng cách nào', 'how', 'PPT Bài 6 · Từ mới', 20, 'published'),
('hsk1-lesson-06-v-w-21', 'hsk1-lesson-06', '坐', 'zuò', null, 'động từ', null, 'đi bằng; ngồi', 'to take; to sit', 'PPT Bài 6 · Từ mới', 21, 'published'),
('hsk1-lesson-06-v-w-22', 'hsk1-lesson-06', '出租车', 'chūzūchē', null, 'danh từ', null, 'taxi', 'taxi', 'PPT Bài 6 · Từ mới', 22, 'published'),
('hsk1-lesson-06-v-w-23', 'hsk1-lesson-06', '西安饭店', 'Xī’ān Fàndiàn', null, 'danh từ riêng', null, 'Nhà hàng Tây An', 'Xi''an Restaurant', 'PPT Bài 6 · Từ mới', 23, 'published'),
('hsk1-lesson-07-v-w-01', 'hsk1-lesson-07', '现在', 'xiànzài', null, 'danh từ thời gian', null, 'bây giờ', 'now', 'PPT Bài 7 · Từ mới', 1, 'published'),
('hsk1-lesson-07-v-w-02', 'hsk1-lesson-07', '点', 'diǎn', null, 'lượng từ', null, 'giờ', 'o''clock', 'PPT Bài 7 · Từ mới', 2, 'published'),
('hsk1-lesson-07-v-w-03', 'hsk1-lesson-07', '早上', 'zǎoshang', null, 'danh từ thời gian', null, 'sáng sớm', 'early morning', 'PPT Bài 7 · Từ mới', 3, 'published'),
('hsk1-lesson-07-v-w-04', 'hsk1-lesson-07', '上午', 'shàngwǔ', null, 'danh từ thời gian', null, 'buổi sáng', 'morning', 'PPT Bài 7 · Từ mới', 4, 'published'),
('hsk1-lesson-07-v-w-05', 'hsk1-lesson-07', '分', 'fēn', null, 'lượng từ', null, 'phút', 'minute', 'PPT Bài 7 · Từ mới', 5, 'published'),
('hsk1-lesson-07-v-w-06', 'hsk1-lesson-07', '课', 'kè', null, 'danh từ', null, 'bài học; tiết học', 'lesson; class', 'PPT Bài 7 · Từ mới', 6, 'published'),
('hsk1-lesson-07-v-w-07', 'hsk1-lesson-07', '下午', 'xiàwǔ', null, 'danh từ thời gian', null, 'buổi chiều', 'afternoon', 'PPT Bài 7 · Từ mới', 7, 'published'),
('hsk1-lesson-07-v-w-08', 'hsk1-lesson-07', '见', 'jiàn', null, 'động từ', null, 'gặp', 'to meet; to see', 'PPT Bài 7 · Từ mới', 8, 'published'),
('hsk1-lesson-07-v-w-09', 'hsk1-lesson-07', '吧', 'ba', null, 'trợ từ', null, 'trợ từ đề nghị', 'suggestion particle', 'PPT Bài 7 · Từ mới', 9, 'published'),
('hsk1-lesson-07-v-w-10', 'hsk1-lesson-07', '电影院', 'diànyǐngyuàn', null, 'danh từ', null, 'rạp chiếu phim', 'cinema', 'PPT Bài 7 · Từ mới', 10, 'published'),
('hsk1-lesson-07-v-w-11', 'hsk1-lesson-07', '看', 'kàn', null, 'động từ', null, 'xem; nhìn; đọc', 'to see; watch; read', 'PPT Bài 7 · Từ mới', 11, 'published'),
('hsk1-lesson-07-v-w-12', 'hsk1-lesson-07', '电影', 'diànyǐng', null, 'danh từ', null, 'phim', 'film; movie', 'PPT Bài 7 · Từ mới', 12, 'published'),
('hsk1-lesson-07-v-w-13', 'hsk1-lesson-07', '事', 'shì', null, 'danh từ', null, 'việc; chuyện', 'matter; affair', 'PPT Bài 7 · Từ mới', 13, 'published'),
('hsk1-lesson-07-v-w-14', 'hsk1-lesson-07', '上课', 'shàngkè', null, 'động từ', null, 'lên lớp; bắt đầu học', 'to attend class', 'PPT Bài 7 · Từ mới', 14, 'published'),
('hsk1-lesson-07-v-w-15', 'hsk1-lesson-07', '呢', 'ne', null, 'trợ từ', null, 'trợ từ xác nhận tình trạng', 'particle indicating an ongoing fact', 'PPT Bài 7 · Từ mới', 15, 'published'),
('hsk1-lesson-07-v-w-16', 'hsk1-lesson-07', '半', 'bàn', null, 'số từ', null, 'nửa; rưỡi', 'half', 'PPT Bài 7 · Từ mới', 16, 'published'),
('hsk1-lesson-07-v-w-17', 'hsk1-lesson-07', '下课', 'xiàkè', null, 'động từ', null, 'tan học', 'to finish class', 'PPT Bài 7 · Từ mới', 17, 'published'),
('hsk1-lesson-07-v-w-18', 'hsk1-lesson-07', '在', 'zài', null, 'động từ', null, 'ở; tại', 'to be at', 'PPT Bài 7 · Từ mới', 18, 'published'),
('hsk1-lesson-07-v-w-19', 'hsk1-lesson-07', '家', 'jiā', null, 'danh từ', null, 'nhà', 'home', 'PPT Bài 7 · Từ mới', 19, 'published'),
('hsk1-lesson-07-v-w-20', 'hsk1-lesson-07', '里', 'lǐ', null, 'danh từ phương vị', null, 'trong; bên trong', 'inside', 'PPT Bài 7 · Từ mới', 20, 'published'),
('hsk1-lesson-07-v-w-21', 'hsk1-lesson-07', '晚上', 'wǎnshang', null, 'danh từ thời gian', null, 'buổi tối', 'evening', 'PPT Bài 7 · Từ mới', 21, 'published'),
('hsk1-lesson-07-v-w-22', 'hsk1-lesson-07', '医院', 'yīyuàn', null, 'danh từ', null, 'bệnh viện', 'hospital', 'PPT Bài 7 · Từ mới', 22, 'published'),
('hsk1-lesson-07-v-w-23', 'hsk1-lesson-07', '上班', 'shàngbān', null, 'động từ', null, 'đi làm', 'to go to work', 'PPT Bài 7 · Từ mới', 23, 'published'),
('hsk1-lesson-07-v-w-24', 'hsk1-lesson-07', '店', 'diàn', null, 'danh từ', null, 'cửa hàng', 'shop', 'PPT Bài 7 · Từ mới', 24, 'published'),
('hsk1-lesson-07-v-w-25', 'hsk1-lesson-07', '菜', 'cài', null, 'danh từ', null, 'rau; món ăn', 'vegetable; dish', 'PPT Bài 7 · Từ mới', 25, 'published'),
('hsk1-lesson-07-v-w-26', 'hsk1-lesson-07', '分钟', 'fēnzhōng', null, 'danh từ', null, 'phút', 'minute', 'PPT Bài 7 · Từ mới', 26, 'published'),
('hsk1-lesson-07-v-w-27', 'hsk1-lesson-07', '后', 'hòu', null, 'danh từ phương vị', null, 'sau', 'after; behind', 'PPT Bài 7 · Từ mới', 27, 'published'),
('hsk1-lesson-08-v-w-01', 'hsk1-lesson-08', '房间', 'fángjiān', null, 'danh từ', null, 'phòng', 'room', 'PPT Bài 8 · Từ mới', 1, 'published'),
('hsk1-lesson-08-v-w-02', 'hsk1-lesson-08', '外', 'wài', null, 'danh từ phương vị', null, 'ngoài; bên ngoài', 'outside', 'PPT Bài 8 · Từ mới', 2, 'published'),
('hsk1-lesson-08-v-w-03', 'hsk1-lesson-08', '只', 'zhī', null, 'lượng từ', null, 'lượng từ chỉ động vật', 'measure word for animals', 'PPT Bài 8 · Từ mới', 3, 'published'),
('hsk1-lesson-08-v-w-04', 'hsk1-lesson-08', '小', 'xiǎo', null, 'tính từ', null, 'nhỏ', 'small', 'PPT Bài 8 · Từ mới', 4, 'published'),
('hsk1-lesson-08-v-w-05', 'hsk1-lesson-08', '猫', 'māo', null, 'danh từ', null, 'mèo', 'cat', 'PPT Bài 8 · Từ mới', 5, 'published'),
('hsk1-lesson-08-v-w-06', 'hsk1-lesson-08', '没', 'méi', null, 'phó từ', null, 'không; chưa', 'not; not yet', 'PPT Bài 8 · Từ mới', 6, 'published'),
('hsk1-lesson-08-v-w-07', 'hsk1-lesson-08', '看见', 'kànjiàn', null, 'động từ', null, 'nhìn thấy', 'to see', 'PPT Bài 8 · Từ mới', 7, 'published'),
('hsk1-lesson-08-v-w-08', 'hsk1-lesson-08', '桌子', 'zhuōzi', null, 'danh từ', null, 'bàn', 'table', 'PPT Bài 8 · Từ mới', 8, 'published'),
('hsk1-lesson-08-v-w-09', 'hsk1-lesson-08', '下', 'xià', null, 'danh từ phương vị', null, 'dưới', 'under; below', 'PPT Bài 8 · Từ mới', 9, 'published'),
('hsk1-lesson-08-v-w-10', 'hsk1-lesson-08', '漂亮', 'piàoliang', null, 'tính từ', null, 'đẹp', 'beautiful', 'PPT Bài 8 · Từ mới', 10, 'published'),
('hsk1-lesson-08-v-w-11', 'hsk1-lesson-08', '在', 'zài', null, 'giới từ / động từ', null, 'ở; tại', 'at; in', 'PPT Bài 8 · Từ mới', 11, 'published'),
('hsk1-lesson-08-v-w-12', 'hsk1-lesson-08', '学校', 'xuéxiào', null, 'danh từ', null, 'trường học', 'school', 'PPT Bài 8 · Từ mới', 12, 'published'),
('hsk1-lesson-08-v-w-13', 'hsk1-lesson-08', '书店', 'shūdiàn', null, 'danh từ', null, 'hiệu sách', 'bookstore', 'PPT Bài 8 · Từ mới', 13, 'published'),
('hsk1-lesson-08-v-w-14', 'hsk1-lesson-08', '前', 'qián', null, 'danh từ phương vị', null, 'trước; phía trước', 'front; before', 'PPT Bài 8 · Từ mới', 14, 'published'),
('hsk1-lesson-08-v-w-15', 'hsk1-lesson-08', '能', 'néng', null, 'động từ năng nguyện', null, 'có thể', 'can; be able to', 'PPT Bài 8 · Từ mới', 15, 'published'),
('hsk1-lesson-08-v-w-16', 'hsk1-lesson-08', '到', 'dào', null, 'động từ', null, 'đến', 'to arrive', 'PPT Bài 8 · Từ mới', 16, 'published'),
('hsk1-lesson-08-v-w-17', 'hsk1-lesson-08', '午饭', 'wǔfàn', null, 'danh từ', null, 'bữa trưa', 'lunch', 'PPT Bài 8 · Từ mới', 17, 'published'),
('hsk1-lesson-08-v-w-18', 'hsk1-lesson-08', '饭', 'fàn', null, 'danh từ', null, 'cơm; bữa ăn', 'meal; rice', 'PPT Bài 8 · Từ mới', 18, 'published'),
('hsk1-lesson-08-v-w-19', 'hsk1-lesson-08', '大', 'dà', null, 'tính từ', null, 'to; lớn', 'big; large', 'PPT Bài 8 · Từ mới', 19, 'published'),
('hsk1-lesson-08-v-w-20', 'hsk1-lesson-08', '病人', 'bìngrén', null, 'danh từ', null, 'bệnh nhân', 'patient', 'PPT Bài 8 · Từ mới', 20, 'published'),
('hsk1-lesson-08-v-w-21', 'hsk1-lesson-08', '多', 'duō', null, 'tính từ', null, 'nhiều', 'many; much', 'PPT Bài 8 · Từ mới', 21, 'published'),
('hsk1-lesson-08-v-w-22', 'hsk1-lesson-08', '医生', 'yīshēng', null, 'danh từ', null, 'bác sĩ', 'doctor', 'PPT Bài 8 · Từ mới', 22, 'published'),
('hsk1-lesson-08-v-w-23', 'hsk1-lesson-08', '工作', 'gōngzuò', null, 'động từ / danh từ', null, 'làm việc; công việc', 'to work; work', 'PPT Bài 8 · Từ mới', 23, 'published'),
('hsk1-lesson-08-v-w-24', 'hsk1-lesson-08', '胡医生', 'Hú yīshēng', null, 'danh từ riêng', null, 'bác sĩ Hồ', 'Doctor Hu', 'PPT Bài 8 · Từ mới', 24, 'published'),
('hsk1-lesson-09-v-w-01', 'hsk1-lesson-09', '前边', 'qiánbian', null, 'danh từ phương vị', null, 'phía trước', 'in front', 'PPT Bài 9 · Từ mới', 1, 'published'),
('hsk1-lesson-09-v-w-02', 'hsk1-lesson-09', '边', 'bian', null, 'hậu tố', null, 'phía; bên', 'side; suffix for location', 'PPT Bài 9 · Từ mới', 2, 'published'),
('hsk1-lesson-09-v-w-03', 'hsk1-lesson-09', '家', 'jiā', null, 'lượng từ', null, 'lượng từ cho cửa hàng, doanh nghiệp', 'measure word for businesses', 'PPT Bài 9 · Từ mới', 3, 'published'),
('hsk1-lesson-09-v-w-04', 'hsk1-lesson-09', '那个', 'nàge', null, 'đại từ', null, 'cái kia; người kia', 'that one', 'PPT Bài 9 · Từ mới', 4, 'published'),
('hsk1-lesson-09-v-w-05', 'hsk1-lesson-09', '外边', 'wàibian', null, 'danh từ phương vị', null, 'bên ngoài', 'outside', 'PPT Bài 9 · Từ mới', 5, 'published'),
('hsk1-lesson-09-v-w-06', 'hsk1-lesson-09', '椅子', 'yǐzi', null, 'danh từ', null, 'ghế', 'chair', 'PPT Bài 9 · Từ mới', 6, 'published'),
('hsk1-lesson-09-v-w-07', 'hsk1-lesson-09', '上', 'shàng', null, 'danh từ phương vị', null, 'trên', 'on; above', 'PPT Bài 9 · Từ mới', 7, 'published'),
('hsk1-lesson-09-v-w-08', 'hsk1-lesson-09', '本', 'běn', null, 'lượng từ', null, 'lượng từ cho sách', 'measure word for books', 'PPT Bài 9 · Từ mới', 8, 'published'),
('hsk1-lesson-09-v-w-09', 'hsk1-lesson-09', '书', 'shū', null, 'danh từ', null, 'sách', 'book', 'PPT Bài 9 · Từ mới', 9, 'published'),
('hsk1-lesson-09-v-w-10', 'hsk1-lesson-09', '那', 'nà', null, 'đại từ', null, 'kia; đó', 'that', 'PPT Bài 9 · Từ mới', 10, 'published'),
('hsk1-lesson-09-v-w-11', 'hsk1-lesson-09', '第', 'dì', null, 'tiền tố', null, 'thứ; tiền tố chỉ thứ tự', 'ordinal prefix', 'PPT Bài 9 · Từ mới', 11, 'published'),
('hsk1-lesson-09-v-w-12', 'hsk1-lesson-09', '学习', 'xuéxí', null, 'động từ', null, 'học tập', 'to study', 'PPT Bài 9 · Từ mới', 12, 'published'),
('hsk1-lesson-09-v-w-13', 'hsk1-lesson-09', '做', 'zuò', null, 'động từ', null, 'làm', 'to do; make', 'PPT Bài 9 · Từ mới', 13, 'published'),
('hsk1-lesson-09-v-w-14', 'hsk1-lesson-09', '白天', 'báitiān', null, 'danh từ thời gian', null, 'ban ngày', 'daytime', 'PPT Bài 9 · Từ mới', 14, 'published'),
('hsk1-lesson-09-v-w-15', 'hsk1-lesson-09', '读书', 'dúshū', null, 'động từ', null, 'đọc sách; đi học', 'to read; to study', 'PPT Bài 9 · Từ mới', 15, 'published'),
('hsk1-lesson-09-v-w-16', 'hsk1-lesson-09', '和', 'hé', null, 'giới từ / liên từ', null, 'cùng với; và', 'with; and', 'PPT Bài 9 · Từ mới', 16, 'published'),
('hsk1-lesson-09-v-w-17', 'hsk1-lesson-09', '朋友', 'péngyou', null, 'danh từ', null, 'bạn bè', 'friend', 'PPT Bài 9 · Từ mới', 17, 'published'),
('hsk1-lesson-09-v-w-18', 'hsk1-lesson-09', '唱', 'chàng', null, 'động từ', null, 'hát', 'to sing', 'PPT Bài 9 · Từ mới', 18, 'published'),
('hsk1-lesson-09-v-w-19', 'hsk1-lesson-09', '歌', 'gē', null, 'danh từ', null, 'bài hát', 'song', 'PPT Bài 9 · Từ mới', 19, 'published'),
('hsk1-lesson-09-v-w-20', 'hsk1-lesson-09', '好听', 'hǎotīng', null, 'tính từ', null, 'hay; dễ nghe', 'pleasant to hear', 'PPT Bài 9 · Từ mới', 20, 'published'),
('hsk1-lesson-09-v-w-21', 'hsk1-lesson-09', '电视', 'diànshì', null, 'danh từ', null, 'tivi', 'television', 'PPT Bài 9 · Từ mới', 21, 'published'),
('hsk1-lesson-09-v-w-22', 'hsk1-lesson-09', '狗', 'gǒu', null, 'danh từ', null, 'chó', 'dog', 'PPT Bài 9 · Từ mới', 22, 'published'),
('hsk1-lesson-09-v-w-23', 'hsk1-lesson-09', '玩', 'wán', null, 'động từ', null, 'chơi', 'to play', 'PPT Bài 9 · Từ mới', 23, 'published'),
('hsk1-lesson-10-v-w-01', 'hsk1-lesson-10', '杯子', 'bēizi', null, 'danh từ', null, 'cốc; ly', 'cup', 'PPT Bài 10 · Từ mới', 1, 'published'),
('hsk1-lesson-10-v-w-02', 'hsk1-lesson-10', '售货员', 'shòuhuòyuán', null, 'danh từ', null, 'nhân viên bán hàng', 'salesperson', 'PPT Bài 10 · Từ mới', 2, 'published'),
('hsk1-lesson-10-v-w-03', 'hsk1-lesson-10', '这边', 'zhèbiān', null, 'đại từ nơi chốn', null, 'phía này; bên này', 'this side; over here', 'PPT Bài 10 · Từ mới', 3, 'published'),
('hsk1-lesson-10-v-w-04', 'hsk1-lesson-10', '钱', 'qián', null, 'danh từ', null, 'tiền', 'money', 'PPT Bài 10 · Từ mới', 4, 'published'),
('hsk1-lesson-10-v-w-05', 'hsk1-lesson-10', '这些', 'zhèxiē', null, 'đại từ', null, 'những cái này', 'these', 'PPT Bài 10 · Từ mới', 5, 'published'),
('hsk1-lesson-10-v-w-06', 'hsk1-lesson-10', '块', 'kuài', null, 'lượng từ', null, 'đồng; tệ (khẩu ngữ)', 'yuan in speech; piece', 'PPT Bài 10 · Từ mới', 6, 'published'),
('hsk1-lesson-10-v-w-07', 'hsk1-lesson-10', '那些', 'nàxiē', null, 'đại từ', null, 'những cái kia', 'those', 'PPT Bài 10 · Từ mới', 7, 'published'),
('hsk1-lesson-10-v-w-08', 'hsk1-lesson-10', '这儿', 'zhèr', null, 'đại từ nơi chốn', null, 'ở đây', 'here', 'PPT Bài 10 · Từ mới', 8, 'published'),
('hsk1-lesson-10-v-w-09', 'hsk1-lesson-10', '水果', 'shuǐguǒ', null, 'danh từ', null, 'hoa quả', 'fruit', 'PPT Bài 10 · Từ mới', 9, 'published'),
('hsk1-lesson-10-v-w-10', 'hsk1-lesson-10', '少', 'shǎo', null, 'tính từ', null, 'ít', 'few; little', 'PPT Bài 10 · Từ mới', 10, 'published'),
('hsk1-lesson-10-v-w-11', 'hsk1-lesson-10', '斤', 'jīn', null, 'lượng từ', null, 'cân Trung Quốc (500 g)', 'jin; 500 grams', 'PPT Bài 10 · Từ mới', 11, 'published'),
('hsk1-lesson-10-v-w-12', 'hsk1-lesson-10', '苹果', 'píngguǒ', null, 'danh từ', null, 'táo', 'apple', 'PPT Bài 10 · Từ mới', 12, 'published'),
('hsk1-lesson-10-v-w-13', 'hsk1-lesson-10', '便宜', 'piányi', null, 'tính từ', null, 'rẻ', 'cheap', 'PPT Bài 10 · Từ mới', 13, 'published'),
('hsk1-lesson-10-v-w-14', 'hsk1-lesson-10', '商店', 'shāngdiàn', null, 'danh từ', null, 'cửa hàng', 'shop; store', 'PPT Bài 10 · Từ mới', 14, 'published'),
('hsk1-lesson-10-v-w-15', 'hsk1-lesson-10', '衣服', 'yīfu', null, 'danh từ', null, 'quần áo', 'clothes', 'PPT Bài 10 · Từ mới', 15, 'published'),
('hsk1-lesson-10-v-w-16', 'hsk1-lesson-10', '件', 'jiàn', null, 'lượng từ', null, 'lượng từ cho quần áo', 'measure word for clothing', 'PPT Bài 10 · Từ mới', 16, 'published'),
('hsk1-lesson-10-v-w-17', 'hsk1-lesson-10', '元', 'yuán', null, 'lượng từ', null, 'nhân dân tệ', 'yuan', 'PPT Bài 10 · Từ mới', 17, 'published'),
('hsk1-lesson-10-v-w-18', 'hsk1-lesson-10', '怎么样', 'zěnmeyàng', null, 'đại từ nghi vấn', null, 'thế nào', 'how; what about', 'PPT Bài 10 · Từ mới', 18, 'published'),
('hsk1-lesson-10-v-w-19', 'hsk1-lesson-10', '贵', 'guì', null, 'tính từ', null, 'đắt', 'expensive', 'PPT Bài 10 · Từ mới', 19, 'published'),
('hsk1-lesson-10-v-w-20', 'hsk1-lesson-10', '穿', 'chuān', null, 'động từ', null, 'mặc', 'to wear', 'PPT Bài 10 · Từ mới', 20, 'published'),
('hsk1-lesson-10-v-w-21', 'hsk1-lesson-10', '女', 'nǚ', null, 'tính từ', null, 'nữ', 'female', 'PPT Bài 10 · Từ mới', 21, 'published'),
('hsk1-lesson-10-v-w-22', 'hsk1-lesson-10', '男', 'nán', null, 'tính từ', null, 'nam', 'male', 'PPT Bài 10 · Từ mới', 22, 'published'),
('hsk1-lesson-10-v-w-23', 'hsk1-lesson-10', '那儿', 'nàr', null, 'đại từ nơi chốn', null, 'ở đó', 'there', 'PPT Bài 10 · Từ mới', 23, 'published'),
('hsk1-lesson-11-v-w-01', 'hsk1-lesson-11', '时候', 'shíhou', null, 'danh từ', null, 'lúc; khi', 'time; moment', 'PPT Bài 11 · Từ mới', 1, 'published'),
('hsk1-lesson-11-v-w-02', 'hsk1-lesson-11', '饭店', 'fàndiàn', null, 'danh từ', null, 'nhà hàng; khách sạn', 'restaurant; hotel', 'PPT Bài 11 · Từ mới', 2, 'published'),
('hsk1-lesson-11-v-w-03', 'hsk1-lesson-11', '知道', 'zhīdào', null, 'động từ', null, 'biết', 'to know', 'PPT Bài 11 · Từ mới', 3, 'published'),
('hsk1-lesson-11-v-w-04', 'hsk1-lesson-11', '正在', 'zhèngzài', null, 'phó từ', null, 'đang', 'currently; in the process of', 'PPT Bài 11 · Từ mới', 4, 'published'),
('hsk1-lesson-11-v-w-05', 'hsk1-lesson-11', '找', 'zhǎo', null, 'động từ', null, 'tìm', 'to look for', 'PPT Bài 11 · Từ mới', 5, 'published'),
('hsk1-lesson-11-v-w-06', 'hsk1-lesson-11', '开车', 'kāichē', null, 'động từ', null, 'lái xe', 'to drive', 'PPT Bài 11 · Từ mới', 6, 'published'),
('hsk1-lesson-11-v-w-07', 'hsk1-lesson-11', '车', 'chē', null, 'danh từ', null, 'xe', 'vehicle; car', 'PPT Bài 11 · Từ mới', 7, 'published'),
('hsk1-lesson-11-v-w-08', 'hsk1-lesson-11', '在', 'zài', null, 'phó từ', null, 'đang', 'in the process of', 'PPT Bài 11 · Từ mới', 8, 'published'),
('hsk1-lesson-11-v-w-09', 'hsk1-lesson-11', '读', 'dú', null, 'động từ', null, 'đọc; theo học', 'to read; to study', 'PPT Bài 11 · Từ mới', 9, 'published'),
('hsk1-lesson-11-v-w-10', 'hsk1-lesson-11', '大学', 'dàxué', null, 'danh từ', null, 'đại học', 'university', 'PPT Bài 11 · Từ mới', 10, 'published'),
('hsk1-lesson-11-v-w-11', 'hsk1-lesson-11', '大学生', 'dàxuéshēng', null, 'danh từ', null, 'sinh viên đại học', 'university student', 'PPT Bài 11 · Từ mới', 11, 'published'),
('hsk1-lesson-11-v-w-12', 'hsk1-lesson-11', '学', 'xué', null, 'động từ', null, 'học', 'to study; learn', 'PPT Bài 11 · Từ mới', 12, 'published'),
('hsk1-lesson-11-v-w-13', 'hsk1-lesson-11', '医', 'yī', null, 'danh từ', null, 'y; y học', 'medicine', 'PPT Bài 11 · Từ mới', 13, 'published'),
('hsk1-lesson-11-v-w-14', 'hsk1-lesson-11', '弟弟', 'dìdi', null, 'danh từ', null, 'em trai', 'younger brother', 'PPT Bài 11 · Từ mới', 14, 'published'),
('hsk1-lesson-11-v-w-15', 'hsk1-lesson-11', '起床', 'qǐchuáng', null, 'động từ', null, 'thức dậy; ra khỏi giường', 'to get up', 'PPT Bài 11 · Từ mới', 15, 'published'),
('hsk1-lesson-11-v-w-16', 'hsk1-lesson-11', '睡觉', 'shuìjiào', null, 'động từ', null, 'ngủ', 'to sleep', 'PPT Bài 11 · Từ mới', 16, 'published'),
('hsk1-lesson-11-v-w-17', 'hsk1-lesson-11', '睡', 'shuì', null, 'động từ', null, 'ngủ', 'to sleep', 'PPT Bài 11 · Từ mới', 17, 'published'),
('hsk1-lesson-11-v-w-18', 'hsk1-lesson-11', '那里', 'nàlǐ', null, 'đại từ nơi chốn', null, 'ở đó', 'there', 'PPT Bài 11 · Từ mới', 18, 'published'),
('hsk1-lesson-11-v-w-19', 'hsk1-lesson-11', '哪里', 'nǎlǐ', null, 'đại từ nghi vấn', null, 'ở đâu', 'where', 'PPT Bài 11 · Từ mới', 19, 'published'),
('hsk1-lesson-11-v-w-20', 'hsk1-lesson-11', '昨天', 'zuótiān', null, 'danh từ thời gian', null, 'hôm qua', 'yesterday', 'PPT Bài 11 · Từ mới', 20, 'published'),
('hsk1-lesson-11-v-w-21', 'hsk1-lesson-11', '问', 'wèn', null, 'động từ', null, 'hỏi', 'to ask', 'PPT Bài 11 · Từ mới', 21, 'published'),
('hsk1-lesson-11-v-w-22', 'hsk1-lesson-11', '对', 'duì', null, 'giới từ', null, 'đối với; hướng về', 'toward; to', 'PPT Bài 11 · Từ mới', 22, 'published'),
('hsk1-lesson-11-v-w-23', 'hsk1-lesson-11', '说', 'shuō', null, 'động từ', null, 'nói', 'to speak; say', 'PPT Bài 11 · Từ mới', 23, 'published'),
('hsk1-lesson-11-v-w-24', 'hsk1-lesson-11', '要', 'yào', null, 'động từ năng nguyện', null, 'muốn; định; sẽ', 'to want; plan to', 'PPT Bài 11 · Từ mới', 24, 'published'),
('hsk1-lesson-11-v-w-25', 'hsk1-lesson-11', '小朋友', 'xiǎopéngyǒu', null, 'danh từ', null, 'trẻ em; bạn nhỏ', 'child', 'PPT Bài 11 · Từ mới', 25, 'published'),
('hsk1-lesson-12-v-w-01', 'hsk1-lesson-12', '天气', 'tiānqì', null, 'danh từ', null, 'thời tiết', 'weather', 'PPT Bài 12 · Từ mới', 1, 'published'),
('hsk1-lesson-12-v-w-02', 'hsk1-lesson-12', '这里', 'zhèlǐ', null, 'đại từ nơi chốn', null, 'ở đây', 'here', 'PPT Bài 12 · Từ mới', 2, 'published'),
('hsk1-lesson-12-v-w-03', 'hsk1-lesson-12', '天', 'tiān', null, 'danh từ / lượng từ', null, 'trời; ngày; lượng từ chỉ ngày', 'weather; day; measure word for days', 'PPT Bài 12 · Từ mới', 3, 'published'),
('hsk1-lesson-12-v-w-04', 'hsk1-lesson-12', '下雨', 'xià yǔ', null, 'động từ', null, 'mưa', 'to rain', 'PPT Bài 12 · Từ mới', 4, 'published'),
('hsk1-lesson-12-v-w-05', 'hsk1-lesson-12', '了', 'le', null, 'trợ từ', null, 'trợ từ biểu thị thay đổi', 'particle indicating change', 'PPT Bài 12 · Từ mới', 5, 'published'),
('hsk1-lesson-12-v-w-06', 'hsk1-lesson-12', '雨', 'yǔ', null, 'danh từ', null, 'mưa', 'rain', 'PPT Bài 12 · Từ mới', 6, 'published'),
('hsk1-lesson-12-v-w-07', 'hsk1-lesson-12', '有点儿', 'yǒudiǎnr', null, 'phó từ', null, 'hơi; có một chút', 'a little; somewhat', 'PPT Bài 12 · Từ mới', 7, 'published'),
('hsk1-lesson-12-v-w-08', 'hsk1-lesson-12', '觉得', 'juéde', null, 'động từ', null, 'cảm thấy', 'to feel; think', 'PPT Bài 12 · Từ mới', 8, 'published'),
('hsk1-lesson-12-v-w-09', 'hsk1-lesson-12', '冷', 'lěng', null, 'tính từ', null, 'lạnh', 'cold', 'PPT Bài 12 · Từ mới', 9, 'published'),
('hsk1-lesson-12-v-w-10', 'hsk1-lesson-12', '下', 'xià', null, 'động từ', null, 'rơi (mưa, tuyết)', 'to fall as rain or snow', 'PPT Bài 12 · Từ mới', 10, 'published'),
('hsk1-lesson-12-v-w-11', 'hsk1-lesson-12', '雪', 'xuě', null, 'danh từ', null, 'tuyết', 'snow', 'PPT Bài 12 · Từ mới', 11, 'published'),
('hsk1-lesson-12-v-w-12', 'hsk1-lesson-12', '来', 'lái', null, 'động từ', null, 'đến', 'to come', 'PPT Bài 12 · Từ mới', 12, 'published'),
('hsk1-lesson-12-v-w-13', 'hsk1-lesson-12', '公司', 'gōngsī', null, 'danh từ', null, 'công ty', 'company', 'PPT Bài 12 · Từ mới', 13, 'published'),
('hsk1-lesson-12-v-w-14', 'hsk1-lesson-12', '生病', 'shēngbìng', null, 'động từ', null, 'bị ốm', 'to fall ill', 'PPT Bài 12 · Từ mới', 14, 'published'),
('hsk1-lesson-12-v-w-15', 'hsk1-lesson-12', '看病', 'kànbìng', null, 'động từ', null, 'đi khám bệnh', 'to see a doctor', 'PPT Bài 12 · Từ mới', 15, 'published'),
('hsk1-lesson-12-v-w-16', 'hsk1-lesson-12', '病', 'bìng', null, 'danh từ / tính từ', null, 'ốm; bệnh', 'illness; sick', 'PPT Bài 12 · Từ mới', 16, 'published'),
('hsk1-lesson-12-v-w-17', 'hsk1-lesson-12', '一点儿', 'yìdiǎnr', null, 'số lượng từ', null, 'một chút', 'a little', 'PPT Bài 12 · Từ mới', 17, 'published'),
('hsk1-lesson-12-v-w-18', 'hsk1-lesson-12', '药', 'yào', null, 'danh từ', null, 'thuốc', 'medicine', 'PPT Bài 12 · Từ mới', 18, 'published'),
('hsk1-lesson-12-v-w-19', 'hsk1-lesson-12', '回', 'huí', null, 'động từ', null, 'trở về', 'to return', 'PPT Bài 12 · Từ mới', 19, 'published'),
('hsk1-lesson-12-v-w-20', 'hsk1-lesson-12', '再', 'zài', null, 'phó từ', null, 'lại; rồi; sau đó', 'again; then', 'PPT Bài 12 · Từ mới', 20, 'published'),
('hsk1-lesson-12-v-w-21', 'hsk1-lesson-12', '喝', 'hē', null, 'động từ', null, 'uống', 'to drink', 'PPT Bài 12 · Từ mới', 21, 'published'),
('hsk1-lesson-12-v-w-22', 'hsk1-lesson-12', '热', 'rè', null, 'tính từ', null, 'nóng', 'hot', 'PPT Bài 12 · Từ mới', 22, 'published'),
('hsk1-lesson-12-v-w-23', 'hsk1-lesson-12', '水', 'shuǐ', null, 'danh từ', null, 'nước', 'water', 'PPT Bài 12 · Từ mới', 23, 'published'),
('hsk1-lesson-13-v-w-01', 'hsk1-lesson-13', '可以', 'kěyǐ', null, 'động từ năng nguyện', null, 'có thể; được phép', 'can; may', 'PPT Bài 13 · Từ mới', 1, 'published'),
('hsk1-lesson-13-v-w-02', 'hsk1-lesson-13', '再', 'zài', null, 'phó từ', null, 'lại; thêm', 'again; another', 'PPT Bài 13 · Từ mới', 2, 'published'),
('hsk1-lesson-13-v-w-03', 'hsk1-lesson-13', '问题', 'wèntí', null, 'danh từ', null, 'câu hỏi; vấn đề', 'question; problem', 'PPT Bài 13 · Từ mới', 3, 'published'),
('hsk1-lesson-13-v-w-04', 'hsk1-lesson-13', '卖', 'mài', null, 'động từ', null, 'bán', 'to sell', 'PPT Bài 13 · Từ mới', 4, 'published'),
('hsk1-lesson-13-v-w-05', 'hsk1-lesson-13', '打电话', 'dǎ diànhuà', null, 'động từ', null, 'gọi điện thoại', 'to make a phone call', 'PPT Bài 13 · Từ mới', 5, 'published'),
('hsk1-lesson-13-v-w-06', 'hsk1-lesson-13', '一下', 'yíxià', null, 'bổ ngữ', null, 'một chút; một lần', 'once; briefly', 'PPT Bài 13 · Từ mới', 6, 'published'),
('hsk1-lesson-13-v-w-07', 'hsk1-lesson-13', '服务员', 'fúwùyuán', null, 'danh từ', null, 'nhân viên phục vụ', 'server; attendant', 'PPT Bài 13 · Từ mới', 7, 'published'),
('hsk1-lesson-13-v-w-08', 'hsk1-lesson-13', '女士', 'nǚshì', null, 'danh từ', null, 'quý cô; quý bà', 'lady; Ms.', 'PPT Bài 13 · Từ mới', 8, 'published'),
('hsk1-lesson-13-v-w-09', 'hsk1-lesson-13', '请', 'qǐng', null, 'động từ', null, 'mời; xin vui lòng', 'please; to invite', 'PPT Bài 13 · Từ mới', 9, 'published'),
('hsk1-lesson-13-v-w-10', 'hsk1-lesson-13', '坐', 'zuò', null, 'động từ', null, 'ngồi', 'to sit', 'PPT Bài 13 · Từ mới', 10, 'published'),
('hsk1-lesson-13-v-w-11', 'hsk1-lesson-13', '给', 'gěi', null, 'động từ', null, 'cho; đưa', 'to give', 'PPT Bài 13 · Từ mới', 11, 'published'),
('hsk1-lesson-13-v-w-12', 'hsk1-lesson-13', '杯', 'bēi', null, 'lượng từ', null, 'cốc; lượng từ cho đồ uống', 'cup; measure word for drinks', 'PPT Bài 13 · Từ mới', 12, 'published'),
('hsk1-lesson-13-v-w-13', 'hsk1-lesson-13', '要', 'yào', null, 'động từ', null, 'muốn; gọi món', 'to want; to order', 'PPT Bài 13 · Từ mới', 13, 'published'),
('hsk1-lesson-13-v-w-14', 'hsk1-lesson-13', '早饭', 'zǎofàn', null, 'danh từ', null, 'bữa sáng', 'breakfast', 'PPT Bài 13 · Từ mới', 14, 'published'),
('hsk1-lesson-13-v-w-15', 'hsk1-lesson-13', '这个', 'zhège', null, 'đại từ', null, 'cái này', 'this one', 'PPT Bài 13 · Từ mới', 15, 'published'),
('hsk1-lesson-13-v-w-16', 'hsk1-lesson-13', '面包', 'miànbāo', null, 'danh từ', null, 'bánh mì', 'bread', 'PPT Bài 13 · Từ mới', 16, 'published'),
('hsk1-lesson-13-v-w-17', 'hsk1-lesson-13', '鸡蛋', 'jīdàn', null, 'danh từ', null, 'trứng gà', 'egg', 'PPT Bài 13 · Từ mới', 17, 'published'),
('hsk1-lesson-13-v-w-18', 'hsk1-lesson-13', '先生', 'xiānsheng', null, 'danh từ', null, 'ông; ngài', 'Mr.; sir', 'PPT Bài 13 · Từ mới', 18, 'published'),
('hsk1-lesson-13-v-w-19', 'hsk1-lesson-13', '一半', 'yíbàn', null, 'số lượng từ', null, 'một nửa', 'one half', 'PPT Bài 13 · Từ mới', 19, 'published'),
('hsk1-lesson-13-v-w-20', 'hsk1-lesson-13', '茶', 'chá', null, 'danh từ', null, 'trà', 'tea', 'PPT Bài 13 · Từ mới', 20, 'published'),
('hsk1-lesson-14-v-w-01', 'hsk1-lesson-14', '上', 'shàng', null, 'động từ', null, 'lên; lên xe; bắt đầu học', 'to board; go up; begin attending', 'PPT Bài 14 · Từ mới', 1, 'published'),
('hsk1-lesson-14-v-w-02', 'hsk1-lesson-14', '火车', 'huǒchē', null, 'danh từ', null, 'tàu hỏa', 'train', 'PPT Bài 14 · Từ mới', 2, 'published'),
('hsk1-lesson-14-v-w-03', 'hsk1-lesson-14', '中午', 'zhōngwǔ', null, 'danh từ thời gian', null, 'buổi trưa', 'noon', 'PPT Bài 14 · Từ mới', 3, 'published'),
('hsk1-lesson-14-v-w-04', 'hsk1-lesson-14', '开', 'kāi', null, 'động từ', null, 'khởi hành; mở', 'to depart; open', 'PPT Bài 14 · Từ mới', 4, 'published'),
('hsk1-lesson-14-v-w-05', 'hsk1-lesson-14', '有些', 'yǒuxiē', null, 'đại từ', null, 'một số', 'some', 'PPT Bài 14 · Từ mới', 5, 'published'),
('hsk1-lesson-14-v-w-06', 'hsk1-lesson-14', '有的', 'yǒude', null, 'đại từ', null, 'có người; có cái', 'some; some of them', 'PPT Bài 14 · Từ mới', 6, 'published'),
('hsk1-lesson-14-v-w-07', 'hsk1-lesson-14', '了', 'le', null, 'trợ từ', null, 'trợ từ chỉ hành động hoàn thành', 'completed-action particle', 'PPT Bài 14 · Từ mới', 7, 'published'),
('hsk1-lesson-14-v-w-08', 'hsk1-lesson-14', '写', 'xiě', null, 'động từ', null, 'viết', 'to write', 'PPT Bài 14 · Từ mới', 8, 'published'),
('hsk1-lesson-14-v-w-09', 'hsk1-lesson-14', '都', 'dōu', null, 'phó từ', null, 'đều; tất cả', 'all; both', 'PPT Bài 14 · Từ mới', 9, 'published'),
('hsk1-lesson-14-v-w-10', 'hsk1-lesson-14', '听见', 'tīngjiàn', null, 'động từ', null, 'nghe thấy', 'to hear', 'PPT Bài 14 · Từ mới', 10, 'published'),
('hsk1-lesson-14-v-w-11', 'hsk1-lesson-14', '不要', 'búyào', null, 'phó từ', null, 'đừng; không được', 'do not', 'PPT Bài 14 · Từ mới', 11, 'published'),
('hsk1-lesson-14-v-w-12', 'hsk1-lesson-14', '说话', 'shuōhuà', null, 'động từ', null, 'nói chuyện', 'to speak; talk', 'PPT Bài 14 · Từ mới', 12, 'published'),
('hsk1-lesson-14-v-w-13', 'hsk1-lesson-14', '听', 'tīng', null, 'động từ', null, 'nghe', 'to listen', 'PPT Bài 14 · Từ mới', 13, 'published'),
('hsk1-lesson-14-v-w-14', 'hsk1-lesson-14', '哪些', 'nǎxiē', null, 'đại từ nghi vấn', null, 'những… nào', 'which ones', 'PPT Bài 14 · Từ mới', 14, 'published'),
('hsk1-lesson-14-v-w-15', 'hsk1-lesson-14', '字', 'zì', null, 'danh từ', null, 'chữ', 'character; written word', 'PPT Bài 14 · Từ mới', 15, 'published'),
('hsk1-lesson-14-v-w-16', 'hsk1-lesson-14', '汉语', 'Hànyǔ', null, 'danh từ', null, 'tiếng Hán; tiếng Trung', 'Chinese language', 'PPT Bài 14 · Từ mới', 16, 'published'),
('hsk1-lesson-14-v-w-17', 'hsk1-lesson-14', '汉字', 'Hànzì', null, 'danh từ', null, 'chữ Hán', 'Chinese character', 'PPT Bài 14 · Từ mới', 17, 'published'),
('hsk1-lesson-14-v-w-18', 'hsk1-lesson-14', '明年', 'míngnián', null, 'danh từ thời gian', null, 'năm sau', 'next year', 'PPT Bài 14 · Từ mới', 18, 'published'),
('hsk1-lesson-14-v-w-19', 'hsk1-lesson-14', '中学', 'zhōngxué', null, 'danh từ', null, 'trường trung học', 'middle school', 'PPT Bài 14 · Từ mới', 19, 'published'),
('hsk1-lesson-14-v-w-20', 'hsk1-lesson-14', '小学', 'xiǎoxué', null, 'danh từ', null, 'trường tiểu học', 'primary school', 'PPT Bài 14 · Từ mới', 20, 'published'),
('hsk1-lesson-14-v-w-21', 'hsk1-lesson-14', '中学生', 'zhōngxuéshēng', null, 'danh từ', null, 'học sinh trung học', 'middle-school student', 'PPT Bài 14 · Từ mới', 21, 'published'),
('hsk1-lesson-14-v-w-22', 'hsk1-lesson-14', '小学生', 'xiǎoxuéshēng', null, 'danh từ', null, 'học sinh tiểu học', 'primary-school student', 'PPT Bài 14 · Từ mới', 22, 'published'),
('hsk1-lesson-14-v-w-23', 'hsk1-lesson-14', '上学', 'shàngxué', null, 'động từ', null, 'đi học', 'to attend school', 'PPT Bài 14 · Từ mới', 23, 'published'),
('hsk1-lesson-14-v-w-24', 'hsk1-lesson-14', '他们', 'tāmen', null, 'đại từ', null, 'họ (nam hoặc hỗn hợp)', 'they; them', 'PPT Bài 14 · Từ mới', 24, 'published'),
('hsk1-lesson-14-v-w-25', 'hsk1-lesson-14', '她们', 'tāmen', null, 'đại từ', null, 'họ (nữ)', 'they; them for females', 'PPT Bài 14 · Từ mới', 25, 'published'),
('hsk1-lesson-14-v-w-26', 'hsk1-lesson-14', '它们', 'tāmen', null, 'đại từ', null, 'chúng (đồ vật, động vật)', 'they; them for non-humans', 'PPT Bài 14 · Từ mới', 26, 'published'),
('hsk1-lesson-14-v-w-27', 'hsk1-lesson-14', '晚', 'wǎn', null, 'tính từ', null, 'muộn', 'late', 'PPT Bài 14 · Từ mới', 27, 'published'),
('hsk1-lesson-15-v-w-01', 'hsk1-lesson-15', '爱', 'ài', null, 'động từ', null, 'yêu; rất thích', 'to love; like', 'PPT Bài 15 · Từ mới', 1, 'published'),
('hsk1-lesson-15-v-w-02', 'hsk1-lesson-15', '哪个', 'nǎge', null, 'đại từ nghi vấn', null, 'cái nào; người nào', 'which one', 'PPT Bài 15 · Từ mới', 2, 'published'),
('hsk1-lesson-15-v-w-03', 'hsk1-lesson-15', '去年', 'qùnián', null, 'danh từ thời gian', null, 'năm ngoái', 'last year', 'PPT Bài 15 · Từ mới', 3, 'published'),
('hsk1-lesson-15-v-w-04', 'hsk1-lesson-15', '男朋友', 'nánpéngyou', null, 'danh từ', null, 'bạn trai', 'boyfriend', 'PPT Bài 15 · Từ mới', 4, 'published'),
('hsk1-lesson-15-v-w-05', 'hsk1-lesson-15', '几', 'jǐ', null, 'đại từ nghi vấn', null, 'mấy; vài', 'how many; several', 'PPT Bài 15 · Từ mới', 5, 'published'),
('hsk1-lesson-15-v-w-06', 'hsk1-lesson-15', '年', 'nián', null, 'danh từ', null, 'năm', 'year', 'PPT Bài 15 · Từ mới', 6, 'published'),
('hsk1-lesson-15-v-w-07', 'hsk1-lesson-15', '好玩儿', 'hǎowánr', null, 'tính từ', null, 'vui; thú vị', 'fun; interesting', 'PPT Bài 15 · Từ mới', 7, 'published'),
('hsk1-lesson-15-v-w-08', 'hsk1-lesson-15', '西安', 'Xī’ān', null, 'danh từ riêng', null, 'Tây An', 'Xi''an', 'PPT Bài 15 · Từ mới', 8, 'published'),
('hsk1-lesson-15-v-w-09', 'hsk1-lesson-15', '北京', 'Běijīng', null, 'danh từ riêng', null, 'Bắc Kinh', 'Beijing', 'PPT Bài 15 · Từ mới', 9, 'published'),
('hsk1-lesson-15-v-w-10', 'hsk1-lesson-15', '飞机', 'fēijī', null, 'danh từ', null, 'máy bay', 'airplane', 'PPT Bài 15 · Từ mới', 10, 'published'),
('hsk1-lesson-15-v-w-11', 'hsk1-lesson-15', '要', 'yào', null, 'động từ', null, 'cần; mất (thời gian)', 'to need; take time', 'PPT Bài 15 · Từ mới', 11, 'published'),
('hsk1-lesson-15-v-w-12', 'hsk1-lesson-15', '小时', 'xiǎoshí', null, 'danh từ', null, 'tiếng; giờ', 'hour', 'PPT Bài 15 · Từ mới', 12, 'published'),
('hsk1-lesson-15-v-w-13', 'hsk1-lesson-15', '家人', 'jiārén', null, 'danh từ', null, 'người nhà; gia đình', 'family member', 'PPT Bài 15 · Từ mới', 13, 'published'),
('hsk1-lesson-15-v-w-14', 'hsk1-lesson-15', '时间', 'shíjiān', null, 'danh từ', null, 'thời gian', 'time', 'PPT Bài 15 · Từ mới', 14, 'published'),
('hsk1-lesson-15-v-w-15', 'hsk1-lesson-15', '机场', 'jīchǎng', null, 'danh từ', null, 'sân bay', 'airport', 'PPT Bài 15 · Từ mới', 15, 'published'),
('hsk1-lesson-15-v-w-16', 'hsk1-lesson-15', '接', 'jiē', null, 'động từ', null, 'đón', 'to pick up; meet', 'PPT Bài 15 · Từ mới', 16, 'published'),
('hsk1-lesson-15-v-w-17', 'hsk1-lesson-15', '住', 'zhù', null, 'động từ', null, 'ở; cư trú', 'to live; stay', 'PPT Bài 15 · Từ mới', 17, 'published'),
('hsk1-lesson-15-v-w-18', 'hsk1-lesson-15', '早', 'zǎo', null, 'tính từ / phó từ', null, 'sớm', 'early', 'PPT Bài 15 · Từ mới', 18, 'published'),
('hsk1-lesson-15-v-w-19', 'hsk1-lesson-15', '那', 'nà', null, 'liên từ', null, 'vậy; thế thì', 'then; in that case', 'PPT Bài 15 · Từ mới', 19, 'published'),
('hsk1-lesson-15-v-w-20', 'hsk1-lesson-15', '大兴机场', 'Dàxīng Jīchǎng', null, 'danh từ riêng', null, 'Sân bay Đại Hưng', 'Daxing Airport', 'PPT Bài 15 · Từ mới', 20, 'published')
on conflict (id) do update set
  hanzi = excluded.hanzi,
  pinyin = excluded.pinyin,
  han_viet = excluded.han_viet,
  part_of_speech_vi = excluded.part_of_speech_vi,
  meaning_vi = excluded.meaning_vi,
  meaning_en = excluded.meaning_en,
  source_note = excluded.source_note,
  sort_order = excluded.sort_order,
  status = excluded.status;


insert into public.exercises (id, lesson_id, section, exercise_type, prompt_vi, prompt_en, prompt_zh, configuration, answer_key, sort_order, status)
values
('hsk1-lesson-02-e-quiz-01', 'hsk1-lesson-02', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “请问”.', 'Choose the correct meaning of “请问”.', '请选择“请问”的正确意思。', '{"choices":[["xin hỏi; cho tôi hỏi","bạn","tên là; gọi","gì"],["excuse me; may I ask","you","to be called; to call","what"],["excuse me; may I ask","you","to be called; to call","what"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-02-e-quiz-02', 'hsk1-lesson-02', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “你”.', 'Choose the correct meaning of “你”.', '请选择“你”的正确意思。', '{"choices":[["bạn","tên là; gọi","gì","tên"],["you","to be called; to call","what","name"],["you","to be called; to call","what","name"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-02-e-quiz-03', 'hsk1-lesson-02', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “叫”.', 'Choose the correct meaning of “叫”.', '请选择“叫”的正确意思。', '{"choices":[["tên là; gọi","gì","tên","tôi"],["to be called; to call","what","name","I; me"],["to be called; to call","what","name","I; me"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-02-e-quiz-04', 'hsk1-lesson-02', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “什么”.', 'Choose the correct meaning of “什么”.', '请选择“什么”的正确意思。', '{"choices":[["gì","tên","tôi","không"],["what","name","I; me","not"],["what","name","I; me","not"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-03-e-quiz-01', 'hsk1-lesson-03', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “人”.', 'Choose the correct meaning of “人”.', '请选择“人”的正确意思。', '{"choices":[["người","trợ từ kết cấu đứng sau thành phần bổ nghĩa","Trung Quốc","Pháp"],["person","structural particle after a modifier","China","France"],["person","structural particle after a modifier","China","France"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-03-e-quiz-02', 'hsk1-lesson-03', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “的”.', 'Choose the correct meaning of “的”.', '请选择“的”的正确意思。', '{"choices":[["trợ từ kết cấu đứng sau thành phần bổ nghĩa","Trung Quốc","Pháp","tiếng Trung"],["structural particle after a modifier","China","France","Chinese language"],["structural particle after a modifier","China","France","Chinese language"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-03-e-quiz-03', 'hsk1-lesson-03', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “中国”.', 'Choose the correct meaning of “中国”.', '请选择“中国”的正确意思。', '{"choices":[["Trung Quốc","Pháp","tiếng Trung","cô ấy"],["China","France","Chinese language","she; her"],["China","France","Chinese language","she; her"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-03-e-quiz-04', 'hsk1-lesson-03', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “法国”.', 'Choose the correct meaning of “法国”.', '请选择“法国”的正确意思。', '{"choices":[["Pháp","tiếng Trung","cô ấy","đây; này"],["France","Chinese language","she; her","this"],["France","Chinese language","she; her","this"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-04-e-quiz-01', 'hsk1-lesson-04', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “有”.', 'Choose the correct meaning of “有”.', '请选择“有”的正确意思。', '{"choices":[["có","bao nhiêu","lượng từ thông dụng","anh trai"],["to have","how many; how much","general measure word","older brother"],["to have","how many; how much","general measure word","older brother"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-04-e-quiz-02', 'hsk1-lesson-04', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “多少”.', 'Choose the correct meaning of “多少”.', '请选择“多少”的正确意思。', '{"choices":[["bao nhiêu","lượng từ thông dụng","anh trai","thế còn…; trợ từ"],["how many; how much","general measure word","older brother","and what about; particle"],["how many; how much","general measure word","older brother","and what about; particle"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-04-e-quiz-03', 'hsk1-lesson-04', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “个”.', 'Choose the correct meaning of “个”.', '请选择“个”的正确意思。', '{"choices":[["lượng từ thông dụng","anh trai","thế còn…; trợ từ","không có"],["general measure word","older brother","and what about; particle","not have; there is not"],["general measure word","older brother","and what about; particle","not have; there is not"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-04-e-quiz-04', 'hsk1-lesson-04', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “哥哥”.', 'Choose the correct meaning of “哥哥”.', '请选择“哥哥”的正确意思。', '{"choices":[["anh trai","thế còn…; trợ từ","không có","gia đình; nhà"],["older brother","and what about; particle","not have; there is not","family; home"],["older brother","and what about; particle","not have; there is not","family; home"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-05-e-quiz-01', 'hsk1-lesson-05', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “今天”.', 'Choose the correct meaning of “今天”.', '请选择“今天”的正确意思。', '{"choices":[["hôm nay","ngày; số","tháng","ngày"],["today","date; number","month","day; date"],["today","date; number","month","day; date"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-05-e-quiz-02', 'hsk1-lesson-05', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “号”.', 'Choose the correct meaning of “号”.', '请选择“号”的正确意思。', '{"choices":[["ngày; số","tháng","ngày","tuần; thứ"],["date; number","month","day; date","week; weekday"],["date; number","month","day; date","week; weekday"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-05-e-quiz-03', 'hsk1-lesson-05', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “月”.', 'Choose the correct meaning of “月”.', '请选择“月”的正确意思。', '{"choices":[["tháng","ngày","tuần; thứ","Chủ nhật"],["month","day; date","week; weekday","Sunday"],["month","day; date","week; weekday","Sunday"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-05-e-quiz-04', 'hsk1-lesson-05', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “日”.', 'Choose the correct meaning of “日”.', '请选择“日”的正确意思。', '{"choices":[["ngày","tuần; thứ","Chủ nhật","Chủ nhật"],["day; date","week; weekday","Sunday","Sunday"],["day; date","week; weekday","Sunday","Sunday"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-06-e-quiz-01', 'hsk1-lesson-06', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “手机”.', 'Choose the correct meaning of “手机”.', '请选择“手机”的正确意思。', '{"choices":[["điện thoại di động","điện thoại; cuộc gọi","số","ngày mai"],["mobile phone","telephone; phone call","number","tomorrow"],["mobile phone","telephone; phone call","number","tomorrow"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-06-e-quiz-02', 'hsk1-lesson-06', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “电话”.', 'Choose the correct meaning of “电话”.', '请选择“电话”的正确意思。', '{"choices":[["điện thoại; cuộc gọi","số","ngày mai","đi"],["telephone; phone call","number","tomorrow","to go"],["telephone; phone call","number","tomorrow","to go"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-06-e-quiz-03', 'hsk1-lesson-06', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “号”.', 'Choose the correct meaning of “号”.', '请选择“号”的正确意思。', '{"choices":[["số","ngày mai","đi","đâu; nơi nào"],["number","tomorrow","to go","where"],["number","tomorrow","to go","where"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-06-e-quiz-04', 'hsk1-lesson-06', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “明天”.', 'Choose the correct meaning of “明天”.', '请选择“明天”的正确意思。', '{"choices":[["ngày mai","đi","đâu; nơi nào","muốn"],["tomorrow","to go","where","to want"],["tomorrow","to go","where","to want"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-07-e-quiz-01', 'hsk1-lesson-07', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “现在”.', 'Choose the correct meaning of “现在”.', '请选择“现在”的正确意思。', '{"choices":[["bây giờ","giờ","sáng sớm","buổi sáng"],["now","o''clock","early morning","morning"],["now","o''clock","early morning","morning"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-07-e-quiz-02', 'hsk1-lesson-07', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “点”.', 'Choose the correct meaning of “点”.', '请选择“点”的正确意思。', '{"choices":[["giờ","sáng sớm","buổi sáng","phút"],["o''clock","early morning","morning","minute"],["o''clock","early morning","morning","minute"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-07-e-quiz-03', 'hsk1-lesson-07', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “早上”.', 'Choose the correct meaning of “早上”.', '请选择“早上”的正确意思。', '{"choices":[["sáng sớm","buổi sáng","phút","bài học; tiết học"],["early morning","morning","minute","lesson; class"],["early morning","morning","minute","lesson; class"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-07-e-quiz-04', 'hsk1-lesson-07', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “上午”.', 'Choose the correct meaning of “上午”.', '请选择“上午”的正确意思。', '{"choices":[["buổi sáng","phút","bài học; tiết học","buổi chiều"],["morning","minute","lesson; class","afternoon"],["morning","minute","lesson; class","afternoon"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-08-e-quiz-01', 'hsk1-lesson-08', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “房间”.', 'Choose the correct meaning of “房间”.', '请选择“房间”的正确意思。', '{"choices":[["phòng","ngoài; bên ngoài","lượng từ chỉ động vật","nhỏ"],["room","outside","measure word for animals","small"],["room","outside","measure word for animals","small"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-08-e-quiz-02', 'hsk1-lesson-08', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “外”.', 'Choose the correct meaning of “外”.', '请选择“外”的正确意思。', '{"choices":[["ngoài; bên ngoài","lượng từ chỉ động vật","nhỏ","mèo"],["outside","measure word for animals","small","cat"],["outside","measure word for animals","small","cat"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-08-e-quiz-03', 'hsk1-lesson-08', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “只”.', 'Choose the correct meaning of “只”.', '请选择“只”的正确意思。', '{"choices":[["lượng từ chỉ động vật","nhỏ","mèo","không; chưa"],["measure word for animals","small","cat","not; not yet"],["measure word for animals","small","cat","not; not yet"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-08-e-quiz-04', 'hsk1-lesson-08', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “小”.', 'Choose the correct meaning of “小”.', '请选择“小”的正确意思。', '{"choices":[["nhỏ","mèo","không; chưa","nhìn thấy"],["small","cat","not; not yet","to see"],["small","cat","not; not yet","to see"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-09-e-quiz-01', 'hsk1-lesson-09', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “前边”.', 'Choose the correct meaning of “前边”.', '请选择“前边”的正确意思。', '{"choices":[["phía trước","phía; bên","lượng từ cho cửa hàng, doanh nghiệp","cái kia; người kia"],["in front","side; suffix for location","measure word for businesses","that one"],["in front","side; suffix for location","measure word for businesses","that one"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-09-e-quiz-02', 'hsk1-lesson-09', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “边”.', 'Choose the correct meaning of “边”.', '请选择“边”的正确意思。', '{"choices":[["phía; bên","lượng từ cho cửa hàng, doanh nghiệp","cái kia; người kia","bên ngoài"],["side; suffix for location","measure word for businesses","that one","outside"],["side; suffix for location","measure word for businesses","that one","outside"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-09-e-quiz-03', 'hsk1-lesson-09', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “家”.', 'Choose the correct meaning of “家”.', '请选择“家”的正确意思。', '{"choices":[["lượng từ cho cửa hàng, doanh nghiệp","cái kia; người kia","bên ngoài","ghế"],["measure word for businesses","that one","outside","chair"],["measure word for businesses","that one","outside","chair"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-09-e-quiz-04', 'hsk1-lesson-09', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “那个”.', 'Choose the correct meaning of “那个”.', '请选择“那个”的正确意思。', '{"choices":[["cái kia; người kia","bên ngoài","ghế","trên"],["that one","outside","chair","on; above"],["that one","outside","chair","on; above"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-10-e-quiz-01', 'hsk1-lesson-10', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “杯子”.', 'Choose the correct meaning of “杯子”.', '请选择“杯子”的正确意思。', '{"choices":[["cốc; ly","nhân viên bán hàng","phía này; bên này","tiền"],["cup","salesperson","this side; over here","money"],["cup","salesperson","this side; over here","money"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-10-e-quiz-02', 'hsk1-lesson-10', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “售货员”.', 'Choose the correct meaning of “售货员”.', '请选择“售货员”的正确意思。', '{"choices":[["nhân viên bán hàng","phía này; bên này","tiền","những cái này"],["salesperson","this side; over here","money","these"],["salesperson","this side; over here","money","these"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-10-e-quiz-03', 'hsk1-lesson-10', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “这边”.', 'Choose the correct meaning of “这边”.', '请选择“这边”的正确意思。', '{"choices":[["phía này; bên này","tiền","những cái này","đồng; tệ (khẩu ngữ)"],["this side; over here","money","these","yuan in speech; piece"],["this side; over here","money","these","yuan in speech; piece"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-10-e-quiz-04', 'hsk1-lesson-10', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “钱”.', 'Choose the correct meaning of “钱”.', '请选择“钱”的正确意思。', '{"choices":[["tiền","những cái này","đồng; tệ (khẩu ngữ)","những cái kia"],["money","these","yuan in speech; piece","those"],["money","these","yuan in speech; piece","those"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-11-e-quiz-01', 'hsk1-lesson-11', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “时候”.', 'Choose the correct meaning of “时候”.', '请选择“时候”的正确意思。', '{"choices":[["lúc; khi","nhà hàng; khách sạn","biết","đang"],["time; moment","restaurant; hotel","to know","currently; in the process of"],["time; moment","restaurant; hotel","to know","currently; in the process of"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-11-e-quiz-02', 'hsk1-lesson-11', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “饭店”.', 'Choose the correct meaning of “饭店”.', '请选择“饭店”的正确意思。', '{"choices":[["nhà hàng; khách sạn","biết","đang","tìm"],["restaurant; hotel","to know","currently; in the process of","to look for"],["restaurant; hotel","to know","currently; in the process of","to look for"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-11-e-quiz-03', 'hsk1-lesson-11', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “知道”.', 'Choose the correct meaning of “知道”.', '请选择“知道”的正确意思。', '{"choices":[["biết","đang","tìm","lái xe"],["to know","currently; in the process of","to look for","to drive"],["to know","currently; in the process of","to look for","to drive"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-11-e-quiz-04', 'hsk1-lesson-11', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “正在”.', 'Choose the correct meaning of “正在”.', '请选择“正在”的正确意思。', '{"choices":[["đang","tìm","lái xe","xe"],["currently; in the process of","to look for","to drive","vehicle; car"],["currently; in the process of","to look for","to drive","vehicle; car"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-12-e-quiz-01', 'hsk1-lesson-12', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “天气”.', 'Choose the correct meaning of “天气”.', '请选择“天气”的正确意思。', '{"choices":[["thời tiết","ở đây","trời; ngày; lượng từ chỉ ngày","mưa"],["weather","here","weather; day; measure word for days","to rain"],["weather","here","weather; day; measure word for days","to rain"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-12-e-quiz-02', 'hsk1-lesson-12', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “这里”.', 'Choose the correct meaning of “这里”.', '请选择“这里”的正确意思。', '{"choices":[["ở đây","trời; ngày; lượng từ chỉ ngày","mưa","trợ từ biểu thị thay đổi"],["here","weather; day; measure word for days","to rain","particle indicating change"],["here","weather; day; measure word for days","to rain","particle indicating change"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-12-e-quiz-03', 'hsk1-lesson-12', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “天”.', 'Choose the correct meaning of “天”.', '请选择“天”的正确意思。', '{"choices":[["trời; ngày; lượng từ chỉ ngày","mưa","trợ từ biểu thị thay đổi","mưa"],["weather; day; measure word for days","to rain","particle indicating change","rain"],["weather; day; measure word for days","to rain","particle indicating change","rain"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-12-e-quiz-04', 'hsk1-lesson-12', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “下雨”.', 'Choose the correct meaning of “下雨”.', '请选择“下雨”的正确意思。', '{"choices":[["mưa","trợ từ biểu thị thay đổi","mưa","hơi; có một chút"],["to rain","particle indicating change","rain","a little; somewhat"],["to rain","particle indicating change","rain","a little; somewhat"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-13-e-quiz-01', 'hsk1-lesson-13', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “可以”.', 'Choose the correct meaning of “可以”.', '请选择“可以”的正确意思。', '{"choices":[["có thể; được phép","lại; thêm","câu hỏi; vấn đề","bán"],["can; may","again; another","question; problem","to sell"],["can; may","again; another","question; problem","to sell"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-13-e-quiz-02', 'hsk1-lesson-13', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “再”.', 'Choose the correct meaning of “再”.', '请选择“再”的正确意思。', '{"choices":[["lại; thêm","câu hỏi; vấn đề","bán","gọi điện thoại"],["again; another","question; problem","to sell","to make a phone call"],["again; another","question; problem","to sell","to make a phone call"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-13-e-quiz-03', 'hsk1-lesson-13', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “问题”.', 'Choose the correct meaning of “问题”.', '请选择“问题”的正确意思。', '{"choices":[["câu hỏi; vấn đề","bán","gọi điện thoại","một chút; một lần"],["question; problem","to sell","to make a phone call","once; briefly"],["question; problem","to sell","to make a phone call","once; briefly"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-13-e-quiz-04', 'hsk1-lesson-13', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “卖”.', 'Choose the correct meaning of “卖”.', '请选择“卖”的正确意思。', '{"choices":[["bán","gọi điện thoại","một chút; một lần","nhân viên phục vụ"],["to sell","to make a phone call","once; briefly","server; attendant"],["to sell","to make a phone call","once; briefly","server; attendant"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-14-e-quiz-01', 'hsk1-lesson-14', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “上”.', 'Choose the correct meaning of “上”.', '请选择“上”的正确意思。', '{"choices":[["lên; lên xe; bắt đầu học","tàu hỏa","buổi trưa","khởi hành; mở"],["to board; go up; begin attending","train","noon","to depart; open"],["to board; go up; begin attending","train","noon","to depart; open"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-14-e-quiz-02', 'hsk1-lesson-14', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “火车”.', 'Choose the correct meaning of “火车”.', '请选择“火车”的正确意思。', '{"choices":[["tàu hỏa","buổi trưa","khởi hành; mở","một số"],["train","noon","to depart; open","some"],["train","noon","to depart; open","some"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-14-e-quiz-03', 'hsk1-lesson-14', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “中午”.', 'Choose the correct meaning of “中午”.', '请选择“中午”的正确意思。', '{"choices":[["buổi trưa","khởi hành; mở","một số","có người; có cái"],["noon","to depart; open","some","some; some of them"],["noon","to depart; open","some","some; some of them"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-14-e-quiz-04', 'hsk1-lesson-14', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “开”.', 'Choose the correct meaning of “开”.', '请选择“开”的正确意思。', '{"choices":[["khởi hành; mở","một số","có người; có cái","trợ từ chỉ hành động hoàn thành"],["to depart; open","some","some; some of them","completed-action particle"],["to depart; open","some","some; some of them","completed-action particle"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published'),
('hsk1-lesson-15-e-quiz-01', 'hsk1-lesson-15', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “爱”.', 'Choose the correct meaning of “爱”.', '请选择“爱”的正确意思。', '{"choices":[["yêu; rất thích","cái nào; người nào","năm ngoái","bạn trai"],["to love; like","which one","last year","boyfriend"],["to love; like","which one","last year","boyfriend"]]}'::jsonb, '{"answer":0}'::jsonb, 1, 'published'),
('hsk1-lesson-15-e-quiz-02', 'hsk1-lesson-15', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “哪个”.', 'Choose the correct meaning of “哪个”.', '请选择“哪个”的正确意思。', '{"choices":[["cái nào; người nào","năm ngoái","bạn trai","mấy; vài"],["which one","last year","boyfriend","how many; several"],["which one","last year","boyfriend","how many; several"]]}'::jsonb, '{"answer":0}'::jsonb, 2, 'published'),
('hsk1-lesson-15-e-quiz-03', 'hsk1-lesson-15', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “去年”.', 'Choose the correct meaning of “去年”.', '请选择“去年”的正确意思。', '{"choices":[["năm ngoái","bạn trai","mấy; vài","năm"],["last year","boyfriend","how many; several","year"],["last year","boyfriend","how many; several","year"]]}'::jsonb, '{"answer":0}'::jsonb, 3, 'published'),
('hsk1-lesson-15-e-quiz-04', 'hsk1-lesson-15', 'quiz', 'multiple-choice', 'Chọn nghĩa đúng của “男朋友”.', 'Choose the correct meaning of “男朋友”.', '请选择“男朋友”的正确意思。', '{"choices":[["bạn trai","mấy; vài","năm","vui; thú vị"],["boyfriend","how many; several","year","fun; interesting"],["boyfriend","how many; several","year","fun; interesting"]]}'::jsonb, '{"answer":0}'::jsonb, 4, 'published')
on conflict (id) do update set
  prompt_vi = excluded.prompt_vi,
  prompt_en = excluded.prompt_en,
  prompt_zh = excluded.prompt_zh,
  configuration = excluded.configuration,
  answer_key = excluded.answer_key,
  sort_order = excluded.sort_order,
  status = excluded.status;

commit;
